### ISSUE TITLE
can i try on Android?

### ISSUE THREAD

**Issue by Natsuki2466** [Rdimo/Hazard-Token-Grabber-V2#101]
i want try but it any have phyton emulator Android?

**Comment by PapaPlantz** [comment]
Please join the discord. https://discord.gg/5vUuxnnp Or contact me on discord. PapaPlantz#3856
And I do not think so.

**Comment by dekrypted** [comment]
> i want try but it any have phyton emulator Android?

I don't think so. Even if there was, Windows and Android function completely different so it may not even work. Sorry!

You could try an android RAT.

**Comment by FuckingToasters** [comment]
> > i want try but it any have phyton emulator Android?
> 
> I don't think so. Even if there was, Windows and Android function completely different so it may not even work. Sorry!
> 
> You could try an android RAT.

stupid? android is based on linux kernal so you can run linux programs. some python scripts support both platforms and it is easy to add support for both however if you want to grab tokens from android users it will work but not with this tool that is made for windows. Windows uses the NTFS Filesystem and Adroid does not. You could get an Windows RDP from Amazon AWS and connect to it using a phoneapp tho.
