### ISSUE TITLE
not opening main.py

### ISSUE THREAD

**Issue by Nadav43p** [Rdimo/Hazard-Token-Grabber-V2#105]
when i open main.py it pops out python after 1 second it closes i have not antivirus installed

**Comment by OoniUni** [comment]
Try viewing the problem by running the file on cmd

**Comment by addi00000** [comment]
You’re probably double clicking the file. Run it from cmd line or make a batch file

**Comment by gazdapajabrunos** [comment]
Don't double click the file , right click on mouse and then open it with notepad or some other code editor
