### ISSUE TITLE
cookies not coming most of the time 

### ISSUE THREAD

**Issue by MeSrabon** [Rdimo/Hazard-Token-Grabber-V2#106]
google chrome cookie not coming most of the time 
is there any fix for that?

**Comment by dekrypted** [comment]
Are you clearing your cookies? If not, try on a different PC and if it’s still not working ask Rdimo

**Comment by MeSrabon** [comment]
almost 100 token is on my discord channel but all comes without cookies only chrome password

**Comment by Rdimo** [comment]
this still the same or?
