### ISSUE TITLE
Windows cannot find build-exe.bat

### ISSUE THREAD

**Issue by cybersenpai69** [Rdimo/Hazard-Token-Grabber-V2#107]
I did everything right up until now, windows cant find the file to run

**Comment by Omexy** [comment]
If that is the case, I would suggest for you to manually compile your file in CMD. Here's how to do that:
1. Go to the folder/directory where everything is located.
2. Remove the path at the top of Windows Explorer and replace it with `cmd` and press Enter.
3. You should then see a CMD window has opened.
4. Type `pyinstaller --onefile --noconsole -i NONE main.py` and replace `main` with what your python script is actually called.
5. After this has been done, your EXE file will be inside a folder called `dist` with the same name as your Python script, but an EXE instead.

Hope this helps! :)
- **Omexy**
