### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by xAzz** [Rdimo/Hazard-Token-Grabber-V2#108]
Windows Defender always seems to be deleting it through virus prot as well

```
Traceback (most recent call last):
  File "main.py", line 440, in <module>
  File "main.py", line 37, in __init__
AttributeError: 'Hazard_Token_Grabber_V2' object has no attribute 'bypass_better_discord'
```

**Comment by Omexy** [comment]
Before compiling the Python script to an EXE file, remove line 37 (`        self.bypass_better_discord()`) and save it. After that you can compile the script and everything should work as it is intended to.

Hope this helps! :)
- **Omexy**
