### ISSUE TITLE
I tried genrating a logger .exe and...

### ISSUE THREAD

**Issue by Shaad777** [Rdimo/Hazard-Token-Grabber-V2#109]
![image](https://user-images.githubusercontent.com/87517435/156190666-99573498-624f-4649-999d-1ce369db758d.png)

that's what it says, am I doing wrong?

**Comment by Pabszito** [comment]
> am I doing wrong?
Yes, the thing you're doing wrong is sharing malware in the first place.

**Comment by Omexy** [comment]
> > am I doing wrong?
> 
> Yes, the thing you're doing wrong is sharing malware in the first place.

Why are you here then? This logger is literally malware uploaded on GitHub and people can ethically experiment with the program, expanding their knowledge on the field of coding in Python, Please do not try to deter people from Rdimo's creations, they wanted to be here in the first place.
 
Now let me help **Shaad** out:
1. Open the original Python file that you are using for the logger (main.py as default).
2. Navigate to lines 36 & 37.
3. Delete the code 
`        if os.path.exists(self.roaming+"\\BetterDiscord\\data\\betterdiscord.asar"):
            self.bypass_better_discord()` from the script. Here is how it looks in the Python file with proper indentation if GitHub has outputted this incorrectly: 
![image](https://user-images.githubusercontent.com/44512200/156461391-628487ec-78ea-4caf-b8c6-1d3fdb772e36.png)

4. Save the Python file.
5. Compile the Python file into an EXE if that is what you wish to do by opening CMD in the directory and inputting `pyinstaller --onefile --clean --noconsole **YOUR PYTHON FILE NAME**.py` into the command line.
6. You should be good to go but your script **will not be able to bypass BetterDiscord's user protection**.

Make sure to reply to this message if it doesn't work; hope it helps! :)

- **Omexy**

**Comment by Pabszito** [comment]
> This logger is literally malware uploaded on GitHub

Reading this already tells that you are dumb as fuck. Go and read [GitHub's Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) before you keep fucking up (and maybe [the community guidelines of Discord](https://discord.com/guidelines) too!). 

This is not educational. Stealing the credit card of someone else isn't educational.  No repository made by Rdimo is educational. A RAT isn't educational. Taking a photo of another person using their webcam without their consent isn't educational. Completely disabling all defense-related settings on an operating system without user consent isn't educational. And this list could go forever.

![image](https://user-images.githubusercontent.com/37744843/156462891-99412288-a4c9-45bc-beb6-986d267890f9.png)

> Please do not try to deter people from Rdimo's creations, they wanted to be here in the first place.

Fuck yeah dude! Let's make the world a better place by stealing the salary of some random dude on the internet (that may even be a child, and the linked credit card may be from his mom or dad). Literally, fuck off.

**Comment by Omexy** [comment]
> > This logger is literally malware uploaded on GitHub
> 
> Reading this already tells that you are dumb as fuck. Go and read [GitHub's Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) before you keep fucking up (and maybe [the community guidelines of Discord](https://discord.com/guidelines) too!).
> 
> This is not educational. Stealing the credit card of someone else isn't educational. No repository made by Rdimo is educational. A RAT isn't educational. Taking a photo of another person using their webcam without their consent isn't educational. Completely disabling all defense-related settings on an operating system without user consent isn't educational. And this list could go forever.
> 
> ![image](https://user-images.githubusercontent.com/37744843/156462891-99412288-a4c9-45bc-beb6-986d267890f9.png)
> 
> > Please do not try to deter people from Rdimo's creations, they wanted to be here in the first place.
> 
> Fuck yeah dude! Let's make the world a better place by stealing the salary of some random dude on the internet (that may even be a child, and the linked credit card may be from his mom or dad). Literally, fuck off.

Okay so this is Rdimo's Token Grabber, which grabs Discord account tokens and it is up to the user what they do with it, Rdimo isn't responsible for the damage that is caused with his programs. And for your information, I've tested this on myself and it **does not** get credit card information, neither any webcam data. I have not tried to use this on anyone else except myself because then I would be breaching many online laws e.g Malicious Communications Act 1988 (UK Law). I use this for purely educational purposes which I can transfer to other programs.
So your argument is valid yet invalid, it can be used for educational purposes if used with the victim's permission or purely on yourself since you have control over your system. I never even said that I was stealing credit cards so I don't know why you're trying to argue that point with me. Don't assume the worst of people who use these products.

- **Omexy**

**Comment by Rdimo** [comment]
> > > This logger is literally malware uploaded on GitHub
> 
> > 
> 
> > Reading this already tells that you are dumb as fuck. Go and read [GitHub's Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) before you keep fucking up (and maybe [the community guidelines of Discord](https://discord.com/guidelines) too!).
> 
> > 
> 
> > This is not educational. Stealing the credit card of someone else isn't educational. No repository made by Rdimo is educational. A RAT isn't educational. Taking a photo of another person using their webcam without their consent isn't educational. Completely disabling all defense-related settings on an operating system without user consent isn't educational. And this list could go forever.
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/37744843/156462891-99412288-a4c9-45bc-beb6-986d267890f9.png)
> 
> > 
> 
> > > Please do not try to deter people from Rdimo's creations, they wanted to be here in the first place.
> 
> > 
> 
> > Fuck yeah dude! Let's make the world a better place by stealing the salary of some random dude on the internet (that may even be a child, and the linked credit card may be from his mom or dad). Literally, fuck off.
> 
> 
> 
> Okay so this is Rdimo's Token Grabber, which grabs Discord account tokens and it is up to the user what they do with it, Rdimo isn't responsible for the damage that is caused with his programs. And for your information, I've tested this on myself and it **does not** get credit card information, neither any webcam data. I have not tried to use this on anyone else except myself because then I would be breaching many online laws e.g Malicious Communications Act 1988 (UK Law). I use this for purely educational purposes which I can transfer to other programs that are non-malicious.
> 
> So your argument is valid yet invalid, it can be used for educational purposes if used with the victim's permission or purely on yourself since you have control over your system. I never even said that I was stealing credit cards so I don't know why you're trying to argue that point with me. Don't assume the worst of people who use these products.
> 
> 
> 
> - **Omexy**

nah dw it does get credit card information from the injection, it's only if they have they add a credit card tho while injection is injected. You get cvc, number, expire date and all of that

**Comment by Omexy** [comment]
> > > > This logger is literally malware uploaded on GitHub
> > 
> > 
> > > 
> > 
> > 
> > > Reading this already tells that you are dumb as fuck. Go and read [GitHub's Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) before you keep fucking up (and maybe [the community guidelines of Discord](https://discord.com/guidelines) too!).
> > 
> > 
> > > 
> > 
> > 
> > > This is not educational. Stealing the credit card of someone else isn't educational. No repository made by Rdimo is educational. A RAT isn't educational. Taking a photo of another person using their webcam without their consent isn't educational. Completely disabling all defense-related settings on an operating system without user consent isn't educational. And this list could go forever.
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/37744843/156462891-99412288-a4c9-45bc-beb6-986d267890f9.png)
> > 
> > 
> > > 
> > 
> > 
> > > > Please do not try to deter people from Rdimo's creations, they wanted to be here in the first place.
> > 
> > 
> > > 
> > 
> > 
> > > Fuck yeah dude! Let's make the world a better place by stealing the salary of some random dude on the internet (that may even be a child, and the linked credit card may be from his mom or dad). Literally, fuck off.
> > 
> > 
> > Okay so this is Rdimo's Token Grabber, which grabs Discord account tokens and it is up to the user what they do with it, Rdimo isn't responsible for the damage that is caused with his programs. And for your information, I've tested this on myself and it **does not** get credit card information, neither any webcam data. I have not tried to use this on anyone else except myself because then I would be breaching many online laws e.g Malicious Communications Act 1988 (UK Law). I use this for purely educational purposes which I can transfer to other programs that are non-malicious.
> > So your argument is valid yet invalid, it can be used for educational purposes if used with the victim's permission or purely on yourself since you have control over your system. I never even said that I was stealing credit cards so I don't know why you're trying to argue that point with me. Don't assume the worst of people who use these products.
> > 
> > * **Omexy**
> 
> nah dw it does get credit card information from the injection, it's only if they have they add a credit card tho while injection is injected. You get cvc, number, expire date and all of that

I mean that's a very slim chance though.

**Comment by Rdimo** [comment]
> > > > > This logger is literally malware uploaded on GitHub
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Reading this already tells that you are dumb as fuck. Go and read [GitHub's Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) before you keep fucking up (and maybe [the community guidelines of Discord](https://discord.com/guidelines) too!).
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > This is not educational. Stealing the credit card of someone else isn't educational. No repository made by Rdimo is educational. A RAT isn't educational. Taking a photo of another person using their webcam without their consent isn't educational. Completely disabling all defense-related settings on an operating system without user consent isn't educational. And this list could go forever.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > ![image](https://user-images.githubusercontent.com/37744843/156462891-99412288-a4c9-45bc-beb6-986d267890f9.png)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > Please do not try to deter people from Rdimo's creations, they wanted to be here in the first place.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Fuck yeah dude! Let's make the world a better place by stealing the salary of some random dude on the internet (that may even be a child, and the linked credit card may be from his mom or dad). Literally, fuck off.
> 
> > > 
> 
> > > 
> 
> > > Okay so this is Rdimo's Token Grabber, which grabs Discord account tokens and it is up to the user what they do with it, Rdimo isn't responsible for the damage that is caused with his programs. And for your information, I've tested this on myself and it **does not** get credit card information, neither any webcam data. I have not tried to use this on anyone else except myself because then I would be breaching many online laws e.g Malicious Communications Act 1988 (UK Law). I use this for purely educational purposes which I can transfer to other programs that are non-malicious.
> 
> > > So your argument is valid yet invalid, it can be used for educational purposes if used with the victim's permission or purely on yourself since you have control over your system. I never even said that I was stealing credit cards so I don't know why you're trying to argue that point with me. Don't assume the worst of people who use these products.
> 
> > > 
> 
> > > * **Omexy**
> 
> > 
> 
> > nah dw it does get credit card information from the injection, it's only if they have they add a credit card tho while injection is injected. You get cvc, number, expire date and all of that
> 
> 
> 
> I mean that's a very slim chance though.

ye but better than hacking into discords database and extracting the shit

**Comment by HidanOnCord** [comment]
rdimo fixed the bug compile it again
