### ISSUE TITLE
Not a bug rather a fix to a bug about better discord

### ISSUE THREAD

**Issue by HidanOnCord** [Rdimo/Hazard-Token-Grabber-V2#110]
if u have this 
![image](https://user-images.githubusercontent.com/100303736/156203616-ba980624-8df5-4ae1-829f-0243e6c9e001.png)
u should go on line 37 where it says   self.bypass_better_discord() replace it with self.bypassBetterDiscord() and if u did it right u wont get any errors if u cant type im sorry gtfo

**Comment by Bananadude3211** [comment]
tyty

**Comment by HidanOnCord** [comment]
i might release a detailed video on how to do it for y’all people who don’t have brain cells and can’t read
