### ISSUE TITLE
Line 2, Module not found error: No module named "requests"

### ISSUE THREAD

**Issue by Awarela** [Rdimo/Hazard-Token-Grabber-V2#111]

**Comment by HidanOnCord** [comment]
join discord and say in general chat help hazard https://discord.gg/Qjys5yu4

**Comment by Pabszito** [comment]
Stop sharing malware and learn how to properly read stack traces/install dependencies.

**Comment by addi00000** [comment]
don't try to hack someone with software you barely understand

**Comment by Awarela** [comment]
how about you sftu and go mind your fucking bussiness you annying cunts

**Comment by OoniUni** [comment]
They aren't wrong tho on God can't use shit u don't understand a simple google search can help with that problem

**Comment by addi00000** [comment]
> how about you sftu and go mind your fucking bussiness you annoying cunts
> 
> by the way thanks HidanOnCord

Okay skid 😂

**Comment by Awarela** [comment]
I'm not a skid, I'm learning, also I'm looking for a way of token log a retard on my school and make him go insane when all his dm get in my discord chan exporter

**Comment by sharkmu** [comment]
hey bro! just type to the cmd: pip install requests

**Comment by Awarela** [comment]
done it! thank u bro
