### ISSUE TITLE
where does output files save in exe file 

### ISSUE THREAD

**Issue by sushant96702** [Rdimo/Hazard-Token-Grabber-V2#116]
where does output files save in exe file

**Comment by Omexy** [comment]
Hey **sushant96702**,

The compiled Python file which will output as an **EXE** file will be saved in a folder inside the directory with the Python file called `dist`.
Hope this helps! :)

- **Omexy**

**Comment by sushant96702** [comment]
ummm my dist folder is empty even after building it

**Comment by Omexy** [comment]
Could you run me through the process of how you build the EXE, preferably with screenshots? It would help me to gain an understanding of what is going on here.

- **Omexy**

**Comment by sushant96702** [comment]
oh i just realised its my pc fault your code is fine ig if u can still help me i would love it

![image](https://user-images.githubusercontent.com/58913117/156977162-53322f6b-6326-4868-b70e-db321ea743bc.png)

**Comment by Omexy** [comment]
Hey again,

Of course I'll try to help you. Contact me on Discord `Omexy#1234` for the support you need.

- **Omexy**
