### ISSUE TITLE
Rdimo please help me :I

### ISSUE THREAD

**Issue by Straight12** [Rdimo/Hazard-Token-Grabber-V2#118]
line 87, in Injection
    os.mkdir(os.path.join(root, name+"\\discord_desktop_core\\Hazard"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\myuser\\AppData\\Local\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Discord\\app-1.0.9004\\modules\\discord_desktop_core-2\\discord_desktop_core\\Hazard'

**Comment by Straight12** [comment]
@Rdimo

**Comment by Rdimo** [comment]
what da hell 😂

**Comment by Straight12** [comment]
idk lol

**Comment by Straight12** [comment]
can i add u on dis?

**Comment by Straight12** [comment]
@Rdimo

**Comment by Straight12** [comment]
broo

**Comment by Straight12** [comment]
rdimo broo

**Comment by Straight12** [comment]
brooo

**Comment by Straight12** [comment]
please help :(( @Rdimo

**Comment by Rdimo** [comment]
helped him on discord
