### ISSUE TITLE
Rdimo pls help

### ISSUE THREAD

**Issue by jyzw544** [Rdimo/Hazard-Token-Grabber-V2#120]
Soo..
![image](https://user-images.githubusercontent.com/101140484/157109892-b7efc296-991e-49da-9ba2-9237dfb5df1c.png)

This is happening and I have no clue why. Anyone help?

**Comment by Rdimo** [comment]
pip install pyinstaller

**Comment by jyzw544** [comment]
i already did

**Comment by jyzw544** [comment]
nvm thanks

**Comment by jyzw544** [comment]
im stupid
