### ISSUE TITLE
Rdimo help still same error after running pip install pyinstaller

### ISSUE THREAD

**Issue by jyzw544** [Rdimo/Hazard-Token-Grabber-V2#121]
I ran pip install pyinstaller and ran the setup.bat file, entered the name and same thing
![image](https://user-images.githubusercontent.com/101140484/157113159-4c2ddf28-663a-46dc-bff9-752fe15d8b0e.png)

**Comment by Straight12** [comment]
pip uninstall pyinstaller and install again idk :\

**Comment by jyzw544** [comment]
i think i have to put something before pyinstaller command idk

**Comment by jyzw544** [comment]
i literally have no clue what's going on rdimo please help

**Comment by addi00000** [comment]
Try prefixing it with `python -m`

**Comment by jyzw544** [comment]
C:\Users\pizzabagel\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: No module named pyinstaller
help

**Comment by addi00000** [comment]
`pip install pyinstaller`
`python -m PyInstaller <arguments>`

**Comment by jyzw544** [comment]
bruhh ok thanks that helped

**Comment by jyzw544** [comment]
closing now
