### ISSUE TITLE
I keep on getting this issue pls help

### ISSUE THREAD

**Issue by NEwdsygfisuyd** [Rdimo/Hazard-Token-Grabber-V2#123]
Can anyone help me please
![Desktop Screenshot 2022 03 07 - 22 53 29 48 (2)](https://user-images.githubusercontent.com/97852576/157132320-d1dc9a8c-bae4-4508-bb3c-6b33e812969c.png)

**Comment by addi00000** [comment]
Install the requirements

**Comment by NEwdsygfisuyd** [comment]
I have but this keeps on happening

**Comment by FuckingToasters** [comment]
> Can anyone help me please ![Desktop Screenshot 2022 03 07 - 22 53 29 48 (2)](https://user-images.githubusercontent.com/97852576/157132320-d1dc9a8c-bae4-4508-bb3c-6b33e812969c.png)

just take a look on the error before asking. it clearly says you not have installed pyinstaller so install it.
