### ISSUE TITLE
Ok , Some issues -

### ISSUE THREAD

**Issue by MrIncognito7** [Rdimo/Hazard-Token-Grabber-V2#124]
1 - the file ran successfully on the victim's pc  webhook also sent me a msg but it didnt include the discord token neither the email or pass  , in general no discord info was sent via webhook

2- You should add support for other browsers too like it sends passwords from chrome, brave, firefox and opera gx support should be added as well..

**Comment by FuckingToasters** [comment]
> 1 - the file ran successfully on the victim's pc webhook also sent me a msg but it didnt include the discord token neither the email or pass , in general no discord info was sent via webhook
> 
> 2- You should add support for other browsers too like it sends passwords from chrome, brave, firefox and opera gx support should be added as well..

are you serious?
It injects itself into discord, it sends some information’s regarding pc, cookies, passwords, location etc.
It is not possible to send discord related stuff automatically. The Victim will be logged out and if the victim logs back in you will get the discord information’s.

**Comment by Rdimo** [comment]
> 1 - the file ran successfully on the victim's pc webhook also sent me a msg but it didnt include the discord token neither the email or pass , in general no discord info was sent via webhook
> 
> 2- You should add support for other browsers too like it sends passwords from chrome, brave, firefox and opera gx support should be added as well..

ye as stated in the readme if you want grabber that grabs from brave, edge, opera etc you need to buy one, not releasing an op logger for free

**Comment by 1stgen** [comment]
ayo send link

**Comment by MrIncognito7** [comment]
> > 1 - the file ran successfully on the victim's pc webhook also sent me a msg but it didnt include the discord token neither the email or pass , in general no discord info was sent via webhook
> > 2- You should add support for other browsers too like it sends passwords from chrome, brave, firefox and opera gx support should be added as well..
> 
> ye as stated in the readme if you want grabber that grabs from brave, edge, opera etc you need to buy one, not releasing an op logger for free

my bad didnt read the whole readme

**Comment by MrIncognito7** [comment]
> 

i dont know how much this is true , when i tried it on my pc discord got closed and i didnt even log in again but it did send all info

**Comment by MrIncognito7** [comment]
> 

i dont know how much this is true , when i tried it on my pc discord got closed and i didnt even log in again but it did send all info

**Comment by MrIncognito7** [comment]
> > 1 - the file ran successfully on the victim's pc webhook also sent me a msg but it didnt include the discord token neither the email or pass , in general no discord info was sent via webhook
> > 2- You should add support for other browsers too like it sends passwords from chrome, brave, firefox and opera gx support should be added as well..
> 
> are you serious? It injects itself into discord, it sends some information’s regarding pc, cookies, passwords, location etc. It is not possible to send discord related stuff automatically. The Victim will be logged out and if the victim logs back in you will get the discord information’s.

i dont know how much this is true , when i tried it on my pc discord got closed and i didnt even log in again but it did send all info

**Comment by MrIncognito7** [comment]
> > 1 - the file ran successfully on the victim's pc webhook also sent me a msg but it didnt include the discord token neither the email or pass , in general no discord info was sent via webhook
> > 2- You should add support for other browsers too like it sends passwords from chrome, brave, firefox and opera gx support should be added as well..
> 
> are you serious? It injects itself into discord, it sends some information’s regarding pc, cookies, passwords, location etc. It is not possible to send discord related stuff automatically. The Victim will be logged out and if the victim logs back in you will get the discord information’s.

The victim did log in back
