### ISSUE TITLE
issue pls check

### ISSUE THREAD

**Issue by Saisuhas652** [Rdimo/Hazard-Token-Grabber-V2#130]
<img width="304" alt="Capture" src="https://user-images.githubusercontent.com/90024371/157625903-b1c564ee-1d8d-4481-aa58-5b849b670d7a.PNG">

**Comment by dekrypted** [comment]
Open the command prompt & made sure you're in the directory of the script
(Do cd {directory}, replace directory with the directory which should look similar to this: C:\Users\DeKrypt\Desktop\Hazard-Token-Grabber-V2)

Then, type "pip install -r requirements.txt"
Finally, run the .py script and see if it works. If it does, you can run "build-exe.bat"

**Good Luck!**

**Comment by euclidsss** [comment]
skid do pip install requests gtfo
