### ISSUE TITLE
where does all the info go? is there a .txt to store your webhook?

### ISSUE THREAD

**Issue by Zardyez** [Rdimo/Hazard-Token-Grabber-V2#132]

**Comment by addi00000** [comment]
It sends a json request to the webhook which posts an embed containing the information into the channel the webhook was created in.

**Comment by Zardyez** [comment]
my question was where i put the webhook.

**Comment by dekrypted** [comment]
> my question was where i put the webhook.

Please be a little more clear in the future.
The webhook goes where it says WEBHOOK_HERE (Hence the name)
Following the usage tutorial on the README.md file should help you!

Let me know if you encounter any issues.

**Comment by Zardyez** [comment]
Im sorry, ive looked far and wide and I cannot find where the webhook is, if its at the very end of the building, the .py automatically closes, so i wouldnt know. (not sure if thats normal.) I've tried redownloading, I really cant find where to put the webhook.

Another note, once I redownloaded, I ran main.py, only for it to crash instantly.

**Comment by Zardyez** [comment]
Right, that second note, i realized i didnt download V2, im sorry im so stupid, anyways i'll look into v2 to see if i can find where to put my webhook.

**Comment by Zardyez** [comment]
Ok, i've checked v2, created a new grabber, yet im not sure where the webhook goes. Is there any fix?
