### ISSUE TITLE
Uh I'm confused

### ISSUE THREAD

**Issue by Digafly** [Rdimo/Hazard-Token-Grabber-V2#133]
The thing isn't working what do I run?
And where is the exe?

**Comment by Digafly** [comment]
![image](https://user-images.githubusercontent.com/98677683/158006389-3fadd310-a875-4a82-9ec4-96904aab92de.png)

Whenever I click in the build-exe it gives me this ^ and when I type the name I want to use, the window exits itself and nothing happens

So how can I fix this?

plus it's not like the other's mine exists and theirs continues with another message. Why does this happen? 

Help...

**Comment by gitiliya** [comment]
prolly cuz your supposed to put in the webhook into the .py file

**Comment by addi00000** [comment]
Run the pyinstaller command from cli

**Comment by Digafly** [comment]
> Run the pyinstaller command from cli

And how do I do that?

**Comment by Digafly** [comment]
> prolly cuz your supposed to put in the webhook into the .py file

I did like 3 times now

**Comment by gitiliya** [comment]
> > prolly cuz your supposed to put in the webhook into the .py file
> 
> 
> 
> I did like 3 times now

Did you download all the requirements?

**Comment by Digafly** [comment]
> > > prolly cuz your supposed to put in the webhook into the .py file
> > 
> > 
> > I did like 3 times now
> 
> Did you download all the requirements?

How?
Cuz I use another web that I think installs the requirements but how do I install requirements with cmd?

**Comment by Digafly** [comment]
WAIT, It worked But I have to find a way to get the password of the Admin so that I can test the file...

**Comment by addi00000** [comment]
> WAIT, It worked But I have to find a way to get the password of the Admin so that I can test the file...
Like UAC?

**Comment by Digafly** [comment]
> > WAIT, It worked But I have to find a way to get the password of the Admin so that I can test the file...
> 
> Like UAC?

Yeah I think so

**Comment by Digafly** [comment]
> > WAIT, It worked But I have to find a way to get the password of the Admin so that I can test the file...
> 
> Like UAC?

Yes UAC (I just searched the name up XD)

**Comment by Digafly** [comment]
Plus why does this file bring in a trojan virus...

I feel uncomfortable now...

**Comment by Digafly** [comment]
But still, I'll try to run that code for the test

Because I have a friend who got hacked and I want to help him, he's begging me for the code so he could get his stuff back, and ive changed some things so that I can get the guy's real Ip and get some extra tokens on his discord if this doesn't work

**Comment by addi00000** [comment]
you should read and understand all the source code before running it
if you feel uncomfortable you shouldn't try to do it
however yes, this will get caught as a trojan because it is
you should obfuscate it first

**Comment by Digafly** [comment]
> obfuscate

How to obfuscate the thing

**Comment by dekrypted** [comment]
Hey there, @Digafly!
The reason the script is detected as a virus is because, well, it is!
But don’t be afraid cause when you run it only you have access to the info, so nobody gets it.
Also, I don’t think you need administrative privileges to run the script? Can you tell me what you are trying to do and what it’s saying.

Thanks! Have a good day.
If you need additional help, you can add me on discord @ DeKrypt#7777

**Comment by Digafly** [comment]
> Hey there, @Digafly! The reason the script is detected as a virus is because, well, it is! But don’t be afraid cause when you run it only you have access to the info, so nobody gets it. Also, I don’t think you need administrative privileges to run the script? Can you tell me what you are trying to do and what it’s saying.
> 
> Thanks! Have a good day. If you need additional help, you can add me on discord @ DeKrypt#7777

Ok
