### ISSUE TITLE
Hazard inst building the exe

### ISSUE THREAD

**Issue by Righted1** [Rdimo/Hazard-Token-Grabber-V2#146]
So i might've came across a bug, which is that it wont build the exe no matter what. i also saw another issue that someone is also failing to build their exe. Any possibly fix?

**Comment by Resisst** [comment]
Can you give more info other than just "It's not building it", is it giving you an error. What does it show?

**Comment by Righted1** [comment]
> Can you give more info other than just "It's not building it", is it giving you an error. What does it show?

Well all it does is when i enter the exe's name, it automatically closes and doesn't build the exe whatsoever.

**Comment by Resisst** [comment]
> > Can you give more info other than just "It's not building it", is it giving you an error. What does it show?
> 
> Well all it does is when i enter the exe's name, it automatically closes and doesn't build the exe whatsoever.

If you're running it directly from the python file then run it from a terminal so you can see the error it outputs.
