### ISSUE TITLE
grab only cookies

### ISSUE THREAD

**Issue by santiagoo997** [Rdimo/Hazard-Token-Grabber-V2#147]
this grab only cookies

**Comment by Rdimo** [comment]
what

**Comment by Resisst** [comment]
poop your mum

**Comment by FuckingToasters** [comment]
> poop your mum

Now to Question is, to who you are talking to? It seems like you are talking to yourself.

**Comment by Resisst** [comment]
> > poop your mum
> 
> Now to Question is, to who you are talking to? It seems like you are talking to yourself.

this is targetted racism

**Comment by FuckingToasters** [comment]
> > > poop your mum
> > 
> > 
> > Now to Question is, to who you are talking to? It seems like you are talking to yourself.
> 
> this is targetted racism

so you now really tell me, that it is targetted racism to say what you wrote back to you? 😂🤷‍♂️

**Comment by Rdimo** [comment]
need more documentation
