### ISSUE TITLE
function question

### ISSUE THREAD

**Issue by Kelxe** [Rdimo/Hazard-Token-Grabber-V2#148]
how can i disable or delete some funcions and leave grab tokens only and remove some others like grab password and cookies so as to make the exe smaller

**Comment by addi00000** [comment]
You’re not going to make the exe much smaller because it has to bundle a python interpreter to run the code. You can obfuscate with some tool to make the code smaller without sacrificing.

**Comment by Kelxe** [comment]
Yes i don't mind sacrificing, for convenience i wanted to have only grabber feature enabled if possible. i tried changing the code a bit or remove some lines but it doesn't seem to compile

**Comment by Rdimo** [comment]
if you want to make the exe smaller I recommend you use [virtualenv](https://pypi.org/project/virtualenv/) (`pip install virtualenv`) and/or upx, if you use both you can get the exe down to like 4mb

**Comment by dekrypted** [comment]
> if you want to make the exe smaller I recommend you use [virtualenv](https://pypi.org/project/virtualenv/) (`pip install virtualenv`) and/or upx, if you use both you can get the exe down to like 4mb

yooo can you send me a tut
