### ISSUE TITLE
fix token grabbing it doesnt get the tokens and also it should be like if you get someones token everytime he creates acc the token should get sended

### ISSUE THREAD

**Issue by chiron852** [Rdimo/Hazard-Token-Grabber-V2#149]

**Comment by Rdimo** [comment]
like the idea that it should send the token if a new acc got created
but as of the token grabbing not working im not quite sure what you mean or how I would fix that since I got no traceback from you and it works fine for me

**Comment by chiron852** [comment]
how does it send token?

**Comment by dekrypted** [comment]
> like the idea that it should send the token if a new acc got created but as of the token grabbing not working im not quite sure what you mean or how I would fix that since I got no traceback from you and it works fine for me

I'm pretty sure the token enc bypass isn't working... At least not for me.

Also the injection will send a new account... No?

**Comment by dekrypted** [comment]
> how does it send token?

Sends it to a discord webhook.

**Comment by chiron852** [comment]
it doesnt for me

**Comment by Rdimo** [comment]
> > like the idea that it should send the token if a new acc got created but as of the token grabbing not working im not quite sure what you mean or how I would fix that since I got no traceback from you and it works fine for me
> 
> I'm pretty sure the token enc bypass isn't working... At least not for me.
> 
> Also the injection will send a new account... No?

token enc bypass is working, or its not even a bypass its just a decrypter that decrypts the encrypted tokens

**Comment by dekrypted** [comment]
> > > like the idea that it should send the token if a new acc got created but as of the token grabbing not working im not quite sure what you mean or how I would fix that since I got no traceback from you and it works fine for me
> > 
> > 
> > I'm pretty sure the token enc bypass isn't working... At least not for me.
> > Also the injection will send a new account... No?
> 
> token enc bypass is working, or its not even a bypass its just a decrypter that decrypts the encrypted tokens

well yeah I know, by bypass I mean updated reflex etc.
so that’s what’s not working. When I run hazard on my pc it ain’t finding no tokens

**Comment by dekrypted** [comment]
> it doesnt for me

Make a discord server, make a webhook, copy it, replace “WEBHOOK_HERE” with it and done. If that doesent work you’re doing something wrong

**Comment by chiron852** [comment]
no im doing everything right it sends everything but not the tokens

**Comment by Rdimo** [comment]
> no im doing everything right it sends everything but not the tokens

updated it a lil bit, redownload it and try again and see, otherwise ill look into it

**Comment by unknown144p** [comment]
Discord password not coming

**Comment by chiron852** [comment]
> Discord password not coming

you cant get password from token grabbing

**Comment by Rdimo** [comment]
> Discord password not coming

if you're talking about the injection, it does still work

**Comment by chiron852** [comment]
still not sending the token also i get a track error when i open python file but it still sends my information except token the error goes so fast i cant even see it

**Comment by Rdimo** [comment]
> still not sending the token also i get a track error when i open python file but it still sends my information except token the error goes so fast i cant even see it

join the [discord](https://cheataway.com/) and let me help you
