### ISSUE TITLE
The Injection is working but it wont send any messages like no email and password

### ISSUE THREAD

**Issue by OudDriver** [Rdimo/Hazard-Token-Grabber-V2#151]

**Comment by Rdimo** [comment]
what

**Comment by OutYT** [comment]
it is like the user log in but then the username and password does not log to webhook

**Comment by Rdimo** [comment]
alr ill look into it

**Comment by OudDriver** [comment]
when this will be fixed?

**Comment by Rdimo** [comment]
> when this will be fixed?

most likely today, upgraded the injection by a huge amount so it's gonne be 10x better

**Comment by OudDriver** [comment]
very epic

**Comment by devturi** [comment]
Facing the same issue, I have only received the screenshot of the victims pc. But nothing else. What could possibly be the issue?

**Comment by Rdimo** [comment]
> Facing the same issue, I have only received the screenshot of the victims pc. But nothing else. What could possibly be the issue?

not sure tbh, works fine for me but if it doesn't work for alot of people ill look into it rn

**Comment by Rdimo** [comment]
ran the logger and messed around with it a little and it worked just fine
