### ISSUE TITLE
token grabber

### ISSUE THREAD

**Issue by N0ji** [Rdimo/Hazard-Token-Grabber-V2#153]
When you get the token grabber from det "hazardnuker" it makes a .py file. is there anyway to make it a exe file, so when they download it you get there tokens and not only if they open the .py file?

**Comment by LocalSmail** [comment]
So you want to make it a exe? I'm confused on what your asking...

**Comment by addi00000** [comment]
> When you get the token grabber from det "hazardnuker" it makes a .py file. is there anyway to make it a exe file, so when they download it you get there tokens and not only if they open the .py file?

PyInstaller
