### ISSUE TITLE
When i try to run the start.bat it says it couldnt find build.exe bat

### ISSUE THREAD

**Issue by demonsdj** [Rdimo/Hazard-Token-Grabber-V2#158]
![Screenshot 2022-03-21 074440](https://user-images.githubusercontent.com/101855333/159197346-fd652d7c-3e5a-4d0a-9fb7-20c5f67549ea.jpg)
pls help @Rdimo

**Comment by Rdimo** [comment]
you need to be in the same directory as the build-exe.bat file
