### ISSUE TITLE
wat shd  i run here

### ISSUE THREAD

**Issue by demonsdj** [Rdimo/Hazard-Token-Grabber-V2#159]
what exe  name shd i enter
![Screenshot 2022-03-21 085351](https://user-images.githubusercontent.com/101855333/159201349-5da6d9c0-8c60-48ce-bd77-509cbe155ed5.jpg)

**Comment by fdsmjkfjires** [comment]
> what exe name shd i enter ![Screenshot 2022-03-21 085351](https://user-images.githubusercontent.com/101855333/159201349-5da6d9c0-8c60-48ce-bd77-509cbe155ed5.jpg)

what ever u want the grabber to be names like nitro,gif,drugs,bitches anything to say the least

**Comment by demonsdj** [comment]
bro ok and wehav to send this exe file to the vitiom right but wen I'm trying to send this discord says file is to powerful exceeding more than 8mb wat shd I do @fossabot @Rdimo

**Comment by Bhuvannn** [comment]
> bro ok and we hav to send this exe file to the victim right but wen I'm trying to send this discord says file is too powerful exceeding more than 8mb wat shd I do @fossabot @Rdimo

Just upload the exe to some online file sharing site like MEGA or anonfiles and send the links to vinctim.

**Comment by Rdimo** [comment]
> bro ok and we hav to send this exe file to the victim right but wen I'm trying to send this discord says file is too powerful exceeding more than 8mb wat shd I do @fossabot @Rdimo



> bro ok and we hav to send this exe file to the victim right but wen I'm trying to send this discord says file is too powerful exceeding more than 8mb wat shd I do @fossabot @Rdimo

[#152](https://github.com/Rdimo/Hazard-Token-Grabber-V2/issues/152)
