### ISSUE TITLE
main.py instantly closes

### ISSUE THREAD

**Issue by TayrasX** [Rdimo/Hazard-Token-Grabber-V2#171]
Whenever I run main.py, before i can put in the webhooks or anything, it instantly closes and I don't know why?

**Comment by mrdidibekfeast** [comment]
same

**Comment by its1mpuleALT** [comment]
youre not supposed to run main.py you need to run build-exe.bat and name your exe than go into the new created folder for your exe. (the folder "dist").

**Comment by Rdimo** [comment]
^^
