### ISSUE TITLE
not grabbing cookies

### ISSUE THREAD

**Issue by its1mpuleALT** [Rdimo/Hazard-Token-Grabber-V2#173]
in the code of main.py i can see that it can steal roblox cookies, but it doesnt create a txt file for them. and for google cookies it isnt updated. it just tells you to go and get hazard gr4bber v2, which is what you just used,

**Comment by Rdimo** [comment]
it does create a txt file for them ([check here #L237](https://github.com/Rdimo/Hazard-Token-Grabber-V2/blob/77e9c11bcab6b93b187e6a0b5bc0954a58da32f0/main.py#L237)) and the google cookies im not really sure, I tried it and t worked just fine but I may be wrong

**Comment by its1mpuleALT** [comment]
when will this be fixed

**Comment by Rdimo** [comment]
> when will this be fixed

idk, not really sure why its happening and its working for me so what can I do

**Comment by its1mpuleALT** [comment]
send me ur main.py i guess.

**Comment by its1mpuleALT** [comment]
> > when will this be fixed
> 
> idk, not really sure why its happening and its working for me so what can I do

just send me your folder

**Comment by FuckingToasters** [comment]
> > > when will this be fixed
> > 
> > 
> > idk, not really sure why its happening and its working for me so what can I do
> 
> just send me your folder

stfu. you are anoying. he said it works so no need to discuss anything else there. it works for me and every other person with an IQ higher than 20

**Comment by its1mpuleALT** [comment]
> > > > when will this be fixed
> > > 
> > > 
> > > idk, not really sure why its happening and its working for me so what can I do
> > 
> > 
> > just send me your folder
> 
> stfu. you are anoying. he said it works so no need to discuss anything else there. it works for me and every other person with an IQ higher than 20

bro. im trying to find why it isnt grabbing cookies. just because it works for you doesnt mean you're smart. why do you think github issues exist?

**Comment by Rdimo** [comment]
ran the logger and it grabbed everything as it should've
