### ISSUE TITLE
Error with setup.bat

### ISSUE THREAD

**Issue by vcbiarjkn** [Rdimo/Hazard-Token-Grabber-V2#175]
I run setup.bat and then i get an error when trying to install future:

`  AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'
  ----------------------------------------
  ERROR: Failed building wheel for future`
How can this be resolved

**Comment by dekrypted** [comment]
1. What version of Python are you using?
2. Do you have any other versions installed?

**Comment by vcbiarjkn** [comment]
3.9, and yes 2.6.

**Comment by Rdimo** [comment]
reinstall python, prob got some issue with wheel

**Comment by dekrypted** [comment]
> 3.9, and yes 2.6.

Uninstall both versions, and reinstall python 3.9.7.
(Make sure to add to path!!)
