### ISSUE TITLE
pls help meh

### ISSUE THREAD

**Issue by discordtokenlogger** [Rdimo/Hazard-Token-Grabber-V2#176]
no idea how to run it, no idea how to do anything here pls help, when i open the "Main" file it just flashes a cmd prompt screen for a split second then disappears and nothing happens, giving 1 month discord nitro classic to ppl who help me

**Comment by clixy1122** [comment]
hey what your discord i will help u on there

**Comment by discordtokenlogger** [comment]
> hey what your discord i will help u on there

ok thanks my discord is . . .#7777

**Comment by discordtokenlogger** [comment]
e

**Comment by clixy1122** [comment]
ok im clixy#6969
