### ISSUE TITLE
Pyinstaller isnt recognized

### ISSUE THREAD

**Issue by Ymez1** [Rdimo/Hazard-Token-Grabber-V2#183]
Name is: TokenLogger
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find C:\Users\yasha\OneDrive\Desktop\Hazard-Token-Grabber-V2-master\TokenLogger.spec

generated exe as TokenLogger.exe
-----------------------------------------------------------------------------------
no exe file appears on my computer.

**Comment by Skymarek** [comment]
do python -m PyInstaller then put the rest of ur stuff

**Comment by dislog6** [comment]
Hey skymarek i have the same problem as the other guy put i tried to do what you said but could you elaborate on "then put the rest if ur stuff" as i don't understand
