### ISSUE TITLE
no module named requests and possibly more

### ISSUE THREAD

**Issue by Skymarek** [Rdimo/Hazard-Token-Grabber-V2#184]
did everything from readme, the victim gets
Traceback (most recent call last):
  File "main.py", line 8, in <module>
ModuleNotFoundError: No module named 'requests'
how would i fix it, i added the icon argument so idk if that changes anything but i have requests installed aswell since u guys say i have to have it installed and they also did pip install requests and same thing

**Comment by Skymarek** [comment]
![image](https://user-images.githubusercontent.com/66534513/161443685-a9910f37-a105-499b-a414-44625cbf502d.png)
 this happens to them now

**Comment by Rdimo** [comment]
already helped you on discord
