### ISSUE TITLE
help

### ISSUE THREAD

**Issue by thatshowpoppin** [Rdimo/Hazard-Token-Grabber-V2#190]
Traceback (most recent call last):
  File "main.py", line 404, in <module>
  File "main.py", line 100, in __init__
  File "main.py", line 118, in injector
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\franu\\AppData\\Local\\Discord\\app-0.0.309\\modules\\discord_desktop_core-2\\discord_desktop_core\\index.js'

**Comment by thatshowpoppin** [comment]
yeah

**Comment by addi00000** [comment]
Are you on windows?

**Comment by addi00000** [comment]
Then there is probably an issue with your discord installation

**Comment by addi00000** [comment]
> your token has been grabbed change your password

?

**Comment by JLZnat** [comment]
oh no sry i was wrong

**Comment by Rdimo** [comment]
this should be fixed now
