### ISSUE TITLE
Problem when I test the logger

### ISSUE THREAD

**Issue by TylerRyno** [Rdimo/Hazard-Token-Grabber-V2#192]
Traceback (most recent call last):
  File "main.py", line 72, in <module>
  File "main.py", line 247, in Hazard_Token_Grabber_V2
TypeError: 'staticmethod' object is not callable

**Comment by Rdimo** [comment]
woopsie daisy, accidently left that, lemme fix

**Comment by Rdimo** [comment]
ight done, ty for telling @TylerRyno

**Comment by TylerRyno** [comment]
> ight done, ty for telling @TylerRyno

thanks for fixing it fast
