### ISSUE TITLE
gimmie credit for token display in webhook

### ISSUE THREAD

**Issue by LocalSmail** [Rdimo/Hazard-Token-Grabber-V2#197]
**![image](https://user-images.githubusercontent.com/96918131/162482708-bc450c37-e0a0-443d-91b3-a66cee3d8998.png)**

please?

**Comment by addi00000** [comment]
You want credit for…

printing an array?

**Comment by LocalSmail** [comment]
yes

**Comment by OoniUni** [comment]
Whatchu gon do if he doesn't?

**Comment by LocalSmail** [comment]
i will jizz in his mother

**Comment by LocalSmail** [comment]
in a polite way ofc

**Comment by Stanley-GF** [comment]
make sence yeah

**Comment by LocalSmail** [comment]
exactly

**Comment by LocalSmail** [comment]
gonna go shower and clean the smegma out of my penis and balls

**Comment by addi00000** [comment]
Respectable

**Comment by LocalSmail** [comment]
back and i still got creamy smegma in my penis and balls

**Comment by Rdimo** [comment]
> gonna go shower and clean the smegma out of my penis and balls

bro you always make those sys ass comments
