### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 3XEQ1E** [Rdimo/Hazard-Token-Grabber-V2#199]
![image](https://user-images.githubusercontent.com/94552766/162543856-35f7730b-15ec-4ac5-903c-2cc8c6b2685a.png)
???

**Comment by Rdimo** [comment]
pip install pyinstaller

**Comment by 3XEQ1E** [comment]
![image](https://user-images.githubusercontent.com/94552766/162546727-1f247dd1-e532-4bfb-9825-015dbff7dd46.png)
still

**Comment by Rdimo** [comment]
py -m pip install pyinstaller

**Comment by Rdimo** [comment]
if that doesn't work install python and add it to path

**Comment by 3XEQ1E** [comment]
it dose the same as the first time

**Comment by 3XEQ1E** [comment]
and i have python installed

**Comment by 3XEQ1E** [comment]
can you help me?
