### ISSUE TITLE
No module named _bootlocale

### ISSUE THREAD

**Issue by LC-iSaucyy** [Rdimo/Hazard-Token-Grabber-V2#207]
raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale
The system cannot find the file specified.
Deleted file - C:\Users\Jadie\OneDrive\Desktop\Hazard-Token-Grabber-V2-master\Teams.exe.spec

**Comment by Rdimo** [comment]
update pyinstaller
`pip install --force-reinstall pyinstaller`
