### ISSUE TITLE
pyinstaller' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by JulesHacks69** [Rdimo/Hazard-Token-Grabber-V2#210]
When i open build-exe.bat and types a name it says: 
Enter the exe name : No

Name is: No
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
Den angivne fil blev ikke fundet.
Den angivne fil blev ikke fundet.
Could Not Find C:\Users\borre\Desktop\Hazard-Token-Grabber-V2-master\No.spec

generated exe as No.exe in the dist folder

Press any key to continue . . .

is there asything i can do?

**Comment by addi00000** [comment]
1. Install Python and add to PATH
2. Run `pip install -r requirements.txt`
