### ISSUE TITLE
No New Discord Login

### ISSUE THREAD

**Issue by quentn0** [Rdimo/Hazard-Token-Grabber-V2#211]
Hi, love your work.

I have a quick question: Is there a way to avoid that the victim doesn't have to log in again every time, but that the file still goes into the startup folder?

Greetings from Germany.

**Comment by Rdimo** [comment]
o, didnt think about that actually, it runs everytime they start their pc which then creates the folder and logging them out

**Comment by Rdimo** [comment]
let me fix this

**Comment by quentn0** [comment]
Thanks for the quick reply, take your time.

**Comment by Rdimo** [comment]
ight fixed this now --> [fixed bug](https://github.com/Rdimo/Hazard-Token-Grabber-V2/commit/a52080c4fb7e29c9c1a94f3fd24b229d44dbe248)

**Comment by quentn0** [comment]
Thanks

**Comment by Evolgate** [comment]
Could you make a program to remove the old file that kills their discord?
