### ISSUE TITLE
index.js PermissionError

### ISSUE THREAD

**Issue by therawest** [Rdimo/Hazard-Token-Grabber-V2#212]
Hello, So I compile .py to .exe but when user runs it 
Errors come out and it does not deliver anything on discord..

`Traceback (most recent call last):
  File "main.py", line 536, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 646, in run_until_complete
  File "main.py", line 139, in init
  File "main.py", line 171, in injector
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\miner\\AppData\\Local\\Discord\\app-1.0.9004\\modules\\discord_desktop_core-2\\discord_desktop_core\\index.js'

Please resolve this or help me out if I am doing something wrong, but I am following steps which you've written.

Check the pic  => **[CLICK FOR PICTURE](https://prnt.sc/Mnt2KSKUFv7X)**
`

**Comment by Rdimo** [comment]
think this is because of your anti-virus, which one you got?

**Comment by therawest** [comment]
I do not have any antivirus and windows defender and realtime protectiond as well eveything else is off.

**Comment by therawest** [comment]
And autorun does not work as well.

**Comment by Rdimo** [comment]
prob cuz the path got cached then

**Comment by therawest** [comment]
So what are you suggesting?
Can you fix that please?

**Comment by dekrypted** [comment]
> So what are you suggesting?
> Can you fix that please?

He's probably working on it. Give it some time.
Also, if you have Discord Token Protector (or anything like that) it ma6 conflict with it.

**Comment by lucasbuyatti** [comment]
Reinstall discord, that worked for me

**Comment by brenden21312131** [comment]
did you ever find a fix

**Comment by Rdimo** [comment]
this is not something I need to fix, just move it somewhere else and try again
