### ISSUE TITLE
Where I can find dist directory

### ISSUE THREAD

**Issue by HeavyDriver3019** [Rdimo/Hazard-Token-Grabber-V2#216]
Running setup.bat is done. Named the .exe file but where i can find that file, it says file is in dist directory. But where is dist directory.

**Comment by addi00000** [comment]
in the same directory as the cmd line you opened

**Comment by HeavyDriver3019** [comment]
Help me!

**Comment by Rdimo** [comment]
didnt u get help

**Comment by HeavyDriver3019** [comment]
No i didn't get it.
