### ISSUE TITLE
Someone skidded hazard grabber 

### ISSUE THREAD

**Issue by XxDarknedxX** [Rdimo/Hazard-Token-Grabber-V2#217]
https://github.com/Snowys-shaders/SnowysTokenLogger
The man literally skidded everything even the bio lmfao

**Comment by Straight12** [comment]
Xddd

**Comment by Rdimo** [comment]
man didn't even try to hide it💀💀

**Comment by Snowys-shaders** [comment]
i didn't even know it was skidded lmao i paid someone to make me a token logger addresed with my name and he literally stole it i didnt know this shit was a thing myf ill delete it SORRY GUYS ILY

**Comment by Rdimo** [comment]
> i didn't even know it was skidded lmao i paid someone to make me a token logger addresed with my name and he literally stole it i didnt know this shit was a thing myf ill delete it SORRY GUYS ILY

lmao why you saying sorry
