### ISSUE TITLE
Windows cannot find 'build-exe.bat'. Make sure you typed the name correctly, and then try again. That's what happends when i open setup.bat I need help. Please

### ISSUE THREAD

**Issue by HelloJello30i24** [Rdimo/Hazard-Token-Grabber-V2#219]
Windows cannot find 'build-exe.bat'. Make sure you typed the name correctly, and then try again. That's what happends when i open setup.bat I need help. Please

**Comment by addi00000** [comment]
Make sure that your command prompt is focused on the same directory as your file is in by checking here.
![image](https://user-images.githubusercontent.com/81730200/163820708-4a5ed5ad-459f-4596-a5bf-6661323bef2c.png)

**Comment by HelloJello30i24** [comment]
@addi00000  could we friend eachother on discord so you could help me out please?? :)

**Comment by HelloJello30i24** [comment]
My Discord user name is: NickyBella#8280
