### ISSUE TITLE
Exe kept getting errors 

### ISSUE THREAD

**Issue by GoldeFinger69420** [Rdimo/Hazard-Token-Grabber-V2#220]
So i did the reinstalling requirements.txt and tried to force reinstall pylauncher but this log kept popping up 
![image](https://user-images.githubusercontent.com/100109038/163939560-ec94db17-6093-4d63-bdf9-68ea5e9b9dd2.png)

**Comment by Rdimo** [comment]
uninstall win32 and then install pypiwin32

**Comment by Rdimo** [comment]
or reinstall pypiwin32, otherwise reinstall python if it doesnt work
