### ISSUE TITLE
is there a way for the logger to run another exe file after the logger runs?

### ISSUE THREAD

**Issue by Sebastianeq142** [Rdimo/Hazard-Token-Grabber-V2#228]
can i make the logger run another exe file after it logs?

**Comment by Rdimo** [comment]
yup

**Comment by Sebastianeq142** [comment]
how to do that?

**Comment by Rdimo** [comment]
different ways but you can either make it download the file and run it, but I'd recommend packing them together if thats the case

**Comment by Rdimo** [comment]
search it up a little and you will find an answer

**Comment by Sebastianeq142** [comment]
ty

**Comment by Evolgate** [comment]
Yes should you do it? If the other exe is detected as a virus by winodws no, better put it all in one with hazard
