### ISSUE TITLE
'pyinstaller' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by x198x** [Rdimo/Hazard-Token-Grabber-V2#234]
someone help pls i have pyinstaller in my python310 scripts folder and also tried 'pip install pyinstaller' and says it is already installed

**Comment by x198x** [comment]
> `python -m PyInstaller`

**Comment by x198x** [comment]
ill try this ive also uninstalled python before to see if that would work

**Comment by x198x** [comment]
![image](https://user-images.githubusercontent.com/103961480/165140159-fef6e96b-bac6-4624-a6a3-65ac72e2b06a.png)
it now says this

**Comment by x198x** [comment]
and this 
![image](https://user-images.githubusercontent.com/103961480/165140520-51a404bb-e7e4-4513-94ee-ef3d977eceb8.png)

**Comment by addi00000** [comment]
`python -m PyInstaller --clean --onefile --noconsole -i NONE main.py`

**Comment by x198x** [comment]
do i need microsoft python or download from website

**Comment by Maywitz** [comment]
whats your discord il help you

**Comment by ringo202** [comment]
> 

i texted u on discord im the ringo202 guy if u could respond that would be amazing

**Comment by TakenStatue** [comment]
Could u help me as well Maywitz?

**Comment by Maywitz** [comment]
yessir whats your discord?
