### ISSUE TITLE
could

### ISSUE THREAD

**Issue by boogieiskool** [Rdimo/Hazard-Token-Grabber-V2#235]
Enter the exe name : cool

Name is: cool
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find C:\Users\Jaymes\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\cool.spec

generated exe as cool.exe in the dist folder

Press any key to continue . . .
------------------------------------------------------------------
this is what came up when I ran the setup.bat
cant find any files, what am I doing wrong?

**Comment by Maywitz** [comment]
whats your discord il help you there

**Comment by boogieiskool** [comment]
Rebrand ed#0069

**Comment by boogieiskool** [comment]
> whats your discord il help you there

Rebrand ed#0069

**Comment by kinggskral** [comment]
I get the same error

**Comment by boogieiskool** [comment]
> I get the same error

Just uninstall python and when you reinstall check all the boxes on the bottom of the installer
