### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by sudOcrypt** [Rdimo/Hazard-Token-Grabber-V2#237]
I get this error after running the built file on my own machine for testing.

--------------------

Traceback (most recent call last):
  File "httpx\_transports\default.py", line 60, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 218, in handle_request
  File "httpcore\_sync\connection_pool.py", line 208, in handle_request
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 539, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 646, in run_until_complete
  File "main.py", line 138, in init
  File "main.py", line 532, in finish
  File "httpx\_api.py", line 304, in post
  File "httpx\_api.py", line 100, in request
  File "httpx\_client.py", line 802, in request
  File "httpx\_client.py", line 889, in send
  File "httpx\_client.py", line 917, in _send_handling_auth
  File "httpx\_client.py", line 954, in _send_handling_redirects
  File "httpx\_client.py", line 990, in _send_single_request
  File "httpx\_transports\default.py", line 217, in handle_request
  File "contextlib.py", line 153, in __exit__
  File "httpx\_transports\default.py", line 77, in map_httpcore_exceptions
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

--------------------
![Traceback error](https://user-images.githubusercontent.com/70650810/165428305-110ea8b3-0f3a-4663-8ceb-ac68586f901e.PNG)

**Comment by Maywitz** [comment]
whats yoru discord il help

**Comment by sudOcrypt** [comment]
> whats yoru discord il help

vanity#1337

**Comment by sudOcrypt** [comment]
> > I get this error after running the built file on my own machine for testing.
> 
> > 
> 
> > Traceback (most recent call last): File "httpx_transports\default.py", line 60, in map_httpcore_exceptions File "httpx_transports\default.py", line 218, in handle_request File "httpcore_sync\connection_pool.py", line 208, in handle_request httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> > 
> 
> > The above exception was the direct cause of the following exception:
> 
> > 
> 
> > Traceback (most recent call last): File "main.py", line 539, in File "asyncio\runners.py", line 44, in run File "asyncio\base_events.py", line 646, in run_until_complete File "main.py", line 138, in init File "main.py", line 532, in finish File "httpx_api.py", line 304, in post File "httpx_api.py", line 100, in request File "httpx_client.py", line 802, in request File "httpx_client.py", line 889, in send File "httpx_client.py", line 917, in _send_handling_auth File "httpx_client.py", line 954, in _send_handling_redirects File "httpx_client.py", line 990, in _send_single_request File "httpx_transports\default.py", line 217, in handle_request File "contextlib.py", line 153, in **exit** File "httpx_transports\default.py", line 77, in map_httpcore_exceptions httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> > 
> 
> > ![Traceback error](https://user-images.githubusercontent.com/70650810/165428305-110ea8b3-0f3a-4663-8ceb-ac68586f901e.PNG)
> 
> 
> 
> you need to put in your webhook 💀

I can't tell if you're slow or not, but I obviously put in the fucking webhook. Add discord I'll screen share breezy#7331

**Comment by Rdimo** [comment]
> > > I get this error after running the built file on my own machine for testing.
> > 
> > 
> > > 
> > 
> > 
> > > Traceback (most recent call last): File "httpx_transports\default.py", line 60, in map_httpcore_exceptions File "httpx_transports\default.py", line 218, in handle_request File "httpcore_sync\connection_pool.py", line 208, in handle_request httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> > 
> > 
> > > 
> > 
> > 
> > > The above exception was the direct cause of the following exception:
> > 
> > 
> > > 
> > 
> > 
> > > Traceback (most recent call last): File "main.py", line 539, in File "asyncio\runners.py", line 44, in run File "asyncio\base_events.py", line 646, in run_until_complete File "main.py", line 138, in init File "main.py", line 532, in finish File "httpx_api.py", line 304, in post File "httpx_api.py", line 100, in request File "httpx_client.py", line 802, in request File "httpx_client.py", line 889, in send File "httpx_client.py", line 917, in _send_handling_auth File "httpx_client.py", line 954, in _send_handling_redirects File "httpx_client.py", line 990, in _send_single_request File "httpx_transports\default.py", line 217, in handle_request File "contextlib.py", line 153, in **exit** File "httpx_transports\default.py", line 77, in map_httpcore_exceptions httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> > 
> > 
> > > 
> > 
> > 
> > > ![Traceback error](https://user-images.githubusercontent.com/70650810/165428305-110ea8b3-0f3a-4663-8ceb-ac68586f901e.PNG)
> > 
> > 
> > you need to put in your webhook 💀
> 
> I can't tell if you're slow or not, but I obviously put in the fucking webhook. Add discord I'll screen share breezy#7331

I can't tell if you can read or not but by the looks of it I'm sure you skipped kindergarten. The traceback clearly displays that the error is occurring in the finish function which is where the info gets sent to the webhook, and it even says that its a **post** request it failed to do, which means that it can only be the webhook since the rest of the requests are **get** requests. Join the [discord](discord.gg/kXFjPzudtY) and ill vc with u

**Comment by sudOcrypt** [comment]
> > > > I get this error after running the built file on my own machine for testing.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Traceback (most recent call last): File "httpx_transports\default.py", line 60, in map_httpcore_exceptions File "httpx_transports\default.py", line 218, in handle_request File "httpcore_sync\connection_pool.py", line 208, in handle_request httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > The above exception was the direct cause of the following exception:
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Traceback (most recent call last): File "main.py", line 539, in File "asyncio\runners.py", line 44, in run File "asyncio\base_events.py", line 646, in run_until_complete File "main.py", line 138, in init File "main.py", line 532, in finish File "httpx_api.py", line 304, in post File "httpx_api.py", line 100, in request File "httpx_client.py", line 802, in request File "httpx_client.py", line 889, in send File "httpx_client.py", line 917, in _send_handling_auth File "httpx_client.py", line 954, in _send_handling_redirects File "httpx_client.py", line 990, in _send_single_request File "httpx_transports\default.py", line 217, in handle_request File "contextlib.py", line 153, in **exit** File "httpx_transports\default.py", line 77, in map_httpcore_exceptions httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > ![Traceback error](https://user-images.githubusercontent.com/70650810/165428305-110ea8b3-0f3a-4663-8ceb-ac68586f901e.PNG)
> 
> > > 
> 
> > > 
> 
> > > you need to put in your webhook 💀
> 
> > 
> 
> > I can't tell if you're slow or not, but I obviously put in the fucking webhook. Add discord I'll screen share breezy#7331
> 
> 
> 
> I can't tell if you can read or not but by the looks of it I'm sure you skipped kindergarten. The traceback clearly displays that the error is occurring in the finish function which is where the info gets sent to the webhook, and it even says that its a **post** request it failed to do, which means that it can only be the webhook since the rest of the requests are **get** requests. Join the [discord](discord.gg/kXFjPzudtY) and ill vc with u

- I'll join cord in like an hour, in school right now.
