### ISSUE TITLE
No module named 'httpx'

### ISSUE THREAD

**Issue by hattyu** [Rdimo/Hazard-Token-Grabber-V2#241]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
ModuleNotFoundError: No module named 'httpx'

**Comment by Maywitz** [comment]
whats your discord il help

**Comment by Rdimo** [comment]
`pip install httpx`, if that doesn't work do `python -m pip install httpx` add python to path if those 2 didn't work otherwise
