### ISSUE TITLE
grab hwid

### ISSUE THREAD

**Issue by p3tt3** [Rdimo/Hazard-Token-Grabber-V2#247]
add an hwid grabber

**Comment by Rdimo** [comment]
what do you expect to do with their hwid

**Comment by p3tt3** [comment]
I can add hwid to blacklisted hwid
> what do you expect to do with their hwid

**Comment by Rdimo** [comment]
okey okey okey okey, alr alr alr alr

**Comment by Rdimo** [comment]
ye good reason actually, didnt think about that

**Comment by hey000hey** [comment]
what is an blacklisted hwid? I'm confused on what it will do

**Comment by logicguy1** [comment]
Look it up, man

**Comment by Rdimo** [comment]
this is now added so closing it
