### ISSUE TITLE
Grab Minecraft accessToken

### ISSUE THREAD

**Issue by p3tt3** [Rdimo/Hazard-Token-Grabber-V2#248]
How about adding a Minecraft cookie/email and password grab?

**Comment by Rdimo** [comment]
I've thought about this actually, to grab minecraft accessTokens. Email:pass is well, ye it explains itself why thats different, but the minecraft accessToken is a thing I think ill add

**Comment by Rdimo** [comment]
woopsie daisy, didnt mean to close

**Comment by cog1233** [comment]
how do i get the enhancement?

**Comment by Rdimo** [comment]
> how do i get the enhancement?

this will probably be added, not now but soon
