### ISSUE TITLE
I don't know if this is an error

### ISSUE THREAD

**Issue by ShitTraesh** [Rdimo/Hazard-Token-Grabber-V2#25]
When i put the name i got this 

Enter the exe name : driver-update

Name is: a
"pyinstaller" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
El sistema no puede encontrar el archivo especificado.
El sistema no puede encontrar el archivo especificado.
No se pudo encontrar C:\Users\Mele\Downloads\Hazard-Token-Grabber-V2-master\driver-update.spec

generated exe as driver-update.exe
and it doesn't generate the .exe 
can you help me pls?

**Comment by ShitTraesh** [comment]
If it is not a inconvenience can you make a short tutorial pls? with all i have to do

**Comment by Rdimo** [comment]
pip install pyinstaller
