### ISSUE TITLE
Is there a way to make fud ?

### ISSUE THREAD

**Issue by XxDarknedxX** [Rdimo/Hazard-Token-Grabber-V2#251]
Is there any way to make it fud ? I tried all kind of obfuscations like pyarmor and even obfuscated the obfuscation and i tried everything but after all i just managed to get 18/61 detection on virustotal 💀

**Comment by Rdimo** [comment]
ye there is, obfuscation does not necessarily make it ud, pyarmor makes it more detected if anything. Learn how anti viruses work and you will see why obfuscation is not gonna make it undetected

**Comment by XxDarknedxX** [comment]
> ye there is, obfuscation does not necessarily make it ud, pyarmor makes it more detected if anything. Learn how anti viruses work and you will see why obfuscation is not gonna make it undetected

Ah okay

**Comment by Rdimo** [comment]
> 

contact me on discord, can help you obfuscate it good and get the detections down to like 3/61 if u want

**Comment by Rdimo** [comment]
but the thing with obfuscation is that the anti viruses will pick the exe up and recognize it as dangerous after a while, which will mean that those 3/61 will probably go to 10/61

**Comment by Rdimo** [comment]
only issue with obfuscation

**Comment by komarek1236** [comment]
bro how to get token

**Comment by XxDarknedxX** [comment]
> bro how to get token

What 💀💀💀
