### ISSUE TITLE
info not sending

### ISSUE THREAD

**Issue by Joshminemod** [Rdimo/Hazard-Token-Grabber-V2#257]
not sending anything to webhook

**Comment by Rdimo** [comment]
> not sending anything to webhook

no errors? no nothing? just doesnt send?

**Comment by azuilol** [comment]
> > not sending anything to webhook
> 
> no errors? no nothing? just doesnt send?

Yeah no error, exe file opens etc but doesn’t webhook to discord

**Comment by Rdimo** [comment]
> > > not sending anything to webhook
> > 
> > 
> > no errors? no nothing? just doesnt send?
> 
> Yeah no error, exe file opens etc but doesn’t webhook to discord

huh, weird. Mind getting on discord and help me figure what the cause might be?

**Comment by Velensky** [comment]
@Rdimo  I ran the program on a test computer and I didnt get any info.happy to get in a vc Nox Arcanum#0232

**Comment by x9o** [comment]
same

**Comment by Rdimo** [comment]
alr mind contacting me on discord and try to help me figure out why? :)

**Comment by x9o** [comment]
sure

**Comment by nizehacking** [comment]
any solution? same here

**Comment by cybernze** [comment]
Hi??

**Comment by Rdimo** [comment]
> Hi??

helo

**Comment by Rdimo** [comment]
havent gotten enough context about this issue so there isn't anything I can go out of since it works for me

**Comment by cybernze** [comment]
When i execute the .exe file that i generated, i don't recieve any message in the discord server.

**Comment by diha174** [comment]
Same problem, if someone can help me, discord: diha#4843

**Comment by x9o** [comment]
I still have this issue

**Comment by Rdimo** [comment]
> When i execute the .exe file that i generated, i don't recieve any message in the discord server.

alr, mind contacting me on [discord](https://cheataway.com/invite)? Would be very grateful if you could help me fix this potential bug
