### ISSUE TITLE
Fix.

### ISSUE THREAD

**Issue by bogzyeet** [Rdimo/Hazard-Token-Grabber-V2#26]
EY, Sup ma guy , this one is a good repo but i think the chrome passwords aren't grabbed, idk why but i found a repo regarding this: https://github.com/agentzex/chrome_v80_password_grabber

so like if u could implement that or a fix for the above mentioned problem , it would be great!! :)

**Comment by Rdimo** [comment]
the code is literally the same xd

**Comment by bogzyeet** [comment]
> the code is literally the same xd

but the passwords arent grabbed , i tried it on 3 different pc's , none works
