### ISSUE TITLE
deleted file?

### ISSUE THREAD

**Issue by aafoo2** [Rdimo/Hazard-Token-Grabber-V2#261]
![image](https://user-images.githubusercontent.com/104758058/167236420-0b6021a9-b72f-4c7c-af36-e0a3a67a736f.png)

**Comment by XxDarknedxX** [comment]
Make sure to disable your anti virus, the screen says that it was created successfully which means is was deleted by another process (anti virus)

**Comment by Iamcoolulikeyouniga** [comment]
Hey, can someone help me With the Token. It's not working and I want to hack a guy that's Racist.

**Comment by aafoo2** [comment]
oh so the mod gets flagged my windows antivirus]
