### ISSUE TITLE
Startup file / Hidden File Locations

### ISSUE THREAD

**Issue by xxeen900** [Rdimo/Hazard-Token-Grabber-V2#263]
Ive run the exe on myself but I without knowing set the startup to true. Where would i be able to locate the startup file or any other hidden file within my files ?

**Comment by Rdimo** [comment]
with startup enabled it just adds it to the startup folder, not in the reg or anything so just go to `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` and make sure you have "hidden items" checked so you can see the file, then just delete it

**Comment by xxeen900** [comment]
> with startup enabled it just adds it to the startup folder, not in the reg or anything so just go to `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` and make sure you have "hidden items" checked so you can see the file, then just delete it

Thank you :)
