### ISSUE TITLE
I am sort of worried about this being a virus or smthin

### ISSUE THREAD

**Issue by NETW0RK-X** [Rdimo/Hazard-Token-Grabber-V2#270]
I know Rdimo is nice and all but i am a bit weary about this. This isnt intended in a rude way. Thank you for answers if I get any

**Comment by Rdimo** [comment]
I mean, I assume you're weary and wondering if its a a virus or malware. Yes it is, but if you're wondering if I put in some hidden function in or something that sends your token to me, you can relax. First of all it's open source so you can see what it does. Still if you don't understand the code, suppose you could search thru the file and see if I put in any discord webhooks or smth in it. Personally I'm not into logging and couldn't really care less about peoples discord info and such but it's good that you're cautious.  DM/VC with me on discord and I'll explain what the code does if you want

**Comment by NETW0RK-X** [comment]
Alright, thank you. You are probably the calmest person I have seen on here.

**Comment by Rdimo** [comment]
> Alright, thank you. You are probably the calmest person I have seen on here.

lmao no worries

**Comment by NETW0RK-X** [comment]
> lmao no worries

Can u add me on discord for any problems?  N3TWORK X#2563

**Comment by Rdimo** [comment]
> 

yaya yaya, sure

**Comment by NETW0RK-X** [comment]
> > 
> 
> yaya yaya, sure

Thanks mate.
