### ISSUE TITLE
Can't run exe

### ISSUE THREAD

**Issue by penmanguy** [Rdimo/Hazard-Token-Grabber-V2#29]
I installed python and it's added to path
All the requirements are downloaded
Pyinstaller is downloaded.

When I run the exe it gives me it says this
![pic1](https://user-images.githubusercontent.com/95002822/143330112-1063889f-5b0c-4381-828b-8895dc05c0a3.PNG)
Yes I called the file Optifine don't worry about that

**Comment by Rdimo** [comment]
do you have Visual C++ Redistributable Package?
