### ISSUE TITLE
grab chrome history and search history

### ISSUE THREAD

**Issue by TeteuXD2** [Rdimo/Hazard-Token-Grabber-V2#300]
if possible

**Comment by Rdimo** [comment]
ye ofc its possible, just didnt add it since I felt like it doesn't really bring any value to grab it, except to laugh at them if they have pornhub in there I suppose

**Comment by Rdimo** [comment]
> thats why i made this suggestion XD

lmao, I mean if alot of people want me to add history I suppose ill do it

**Comment by splitparadcx** [comment]
since you aren't actually adding anything new can someone actually make this specific grab

**Comment by TeteuXD2** [comment]
how he don't add any new? 

"v1.7.0 ⋮ 2022-05-22
+ Added support for https://github.com/Rdimo/Discord-Webhook-Protector"

o-o

**Comment by Rdimo** [comment]
> since you aren't actually adding anything new can someone actually make this specific grab

what

**Comment by TeteuXD2** [comment]
btw, i need a litte help, so i sent you a discord friend request

**Comment by TeteuXD2** [comment]
sevach#9767
