### ISSUE TITLE
Minecraft account stealer

### ISSUE THREAD

**Issue by RandomVersion** [Rdimo/Hazard-Token-Grabber-V2#306]
mojang/microsoft + diffrent launchers

**Comment by Snipeeeey** [comment]
Minecraft accounts are often saved in the Browser, just look for them in GooglePasswords.txt

**Comment by RandomVersion** [comment]
Well yes, but not **always** which could be a problem so it would be nice to grab them directly from the launchers and then include them into the zip

**Comment by addi00000** [comment]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/81730200/169070475-c69bc272-8ead-4b4d-a261-bb4586b5e1c0.png">

**Comment by Rdimo** [comment]
#248
