### ISSUE TITLE
Info not sending to Webhook

### ISSUE THREAD

**Issue by diha174** [Rdimo/Hazard-Token-Grabber-V2#310]
When I open the Created .exe in dist, nothing shows up in the discord channel.

**Comment by elmoelmo1** [comment]
Very vague question.

**Comment by PandoricGalaxy** [comment]
> When I open the Created .exe in dist, nothing shows up in the discord channel.

u entered correct webhook link?

**Comment by PandoricGalaxy** [comment]
> > > When I open the Created .exe in dist, nothing shows up in the discord channel.
> > 
> > 
> > u entered correct webhook link?
> 
> Yeah I entered correct webhook link I copied and past it somewhere else it worked but It didnt work with this script.

Show your config

**Comment by PandoricGalaxy** [comment]
Umm u need help?

**Comment by diha174** [comment]
> Umm u need help?

Yes I need

**Comment by PandoricGalaxy** [comment]
Did u enter right webhook and are using the latest version of hazard v2?

**Comment by diha174** [comment]
Yes, I used last version and I entered the right webhook.

**Comment by diha174** [comment]
> Did u enter right webhook and are using the latest version of hazard v2?

Yes, I used last version and I entered the right webhook.

**Comment by PandoricGalaxy** [comment]
Run the .py file from cmd and tell me if any error appears

**Comment by diha174** [comment]
> Run the .py file from cmd and tell me if any error appears

How do I run the .py file from cmd?

**Comment by PandoricGalaxy** [comment]
Just open cmd in the dir of your grabber and then type the name of the grabber like type main.py in cmd in the dir of your grabber

**Comment by PandoricGalaxy** [comment]
The cmd shouldn't close.. open cmd by searching cmd in search then cd into your hazard dir then run main.py it shouldn't close the cmd window

**Comment by diha174** [comment]
> 
I tried it more then 20 times still closes, I run cmd a admin - cd (file path to hazard")- start main.py- another cmd pops up and after 1 sec it closes

**Comment by diha174** [comment]
> > 
> 
> I tried it more then 20 times still closes, I run cmd a admin - cd (file path to hazard")- start main.py- another cmd pops up and after 1 sec it closes


I tried it more then 20 times still closes, I run cmd a admin - cd (file path to hazard")- start main.py- another cmd pops up and after 1 sec it closes

**Comment by diha174** [comment]
> The cmd shouldn't close.. open cmd by searching cmd in search then cd into your hazard dir then run main.py it shouldn't close the cmd window


I tried it more then 20 times still closes, I run cmd a admin - cd (file path to hazard")- start main.py- another cmd pops up and after 1 sec it closes

**Comment by Rdimo** [comment]
> > The cmd shouldn't close.. open cmd by searching cmd in search then cd into your hazard dir then run main.py it shouldn't close the cmd window
> 
> I tried it more then 20 times still closes, I run cmd a admin - cd (file path to hazard")- start main.py- another cmd pops up and after 1 sec it closes

dont run cmd as admin

**Comment by Rdimo** [comment]
you current directory will change to sys32 which then will get filenotfound error

**Comment by diha174** [comment]
> > > The cmd shouldn't close.. open cmd by searching cmd in search then cd into your hazard dir then run main.py it shouldn't close the cmd window
> > 
> > 
> > I tried it more then 20 times still closes, I run cmd a admin - cd (file path to hazard")- start main.py- another cmd pops up and after 1 sec it closes
> 
> dont run cmd as admin

I did without and still closes

**Comment by PandoricGalaxy** [comment]
> > > > The cmd shouldn't close.. open cmd by searching cmd in search then cd into your hazard dir then run main.py it shouldn't close the cmd window
> > > 
> > > 
> > > I tried it more then 20 times still closes, I run cmd a admin - cd (file path to hazard")- start main.py- another cmd pops up and after 1 sec it closes
> > 
> > 
> > dont run cmd as admin
> 
> I did without and still closes

U sure it was cmd and not powershell?

**Comment by euclidsss** [comment]
are you running in a vm? if so, rdimo purposely added protection against that. meaning it closes automatically if opened in a vm

**Comment by xylo101** [comment]
> are you running in a vm? if so, rdimo purposely added protection against that. meaning it closes automatically if opened in a vm

no

**Comment by PandoricGalaxy** [comment]
> 

Run it via cmd and show me video of u running it on cmd and it auto closing

**Comment by abdou5252** [comment]
same problom

**Comment by Voltayn** [comment]
i've found out a solution, i just deleted the list from blackListedPrograms l.47 in main.py and it worked

**Comment by PandoricGalaxy** [comment]
That's not a solution... U are basically destroying the killBlackListed programs feature. Dont delete the list just turn it off from config. The problem occurs in the first place since u might be testing it in a vm and the anti-vm detects it and turns it self off so u don't get info on webhook. Run on your own system and check

**Comment by Rdimo** [comment]
ye, im trying to look into why/how people get this but it just "doesn't run" for them, luckily its only like 3 people who contacted me having this issue but im trying my best to atleast see if I can fix it

**Comment by euclidsss** [comment]
its because they are using antidebug on a vm lol-- 
Matrix: @euclid:midov.pl
Discord: euclid#8084
Sent with Tutanota

23 June 2022, 11:11 pm by ***@***.***:

**Comment by euclidsss** [comment]
ah aight.surprised anyone still uses the nuker anyways.-- 
Matrix: @euclid:midov.pl
Discord: euclid#8084
Sent with Tutanota

23 June 2022, 11:31 pm by ***@***.***:
