### ISSUE TITLE
No module named 'Crypto'

### ISSUE THREAD

**Issue by Sina121123** [Rdimo/Hazard-Token-Grabber-V2#323]
i have this issue using my build
i have installed all the requirments,and idrk why i get this error related to the imports
![image](https://user-images.githubusercontent.com/88611114/169836944-a56e57ce-54e7-4efd-a534-39c13defa1d1.png)

**Comment by Rdimo** [comment]
> i have this issue using my build i have installed all the requirments,and idrk why i get this error related to the imports ![image](https://user-images.githubusercontent.com/88611114/169836944-a56e57ce-54e7-4efd-a534-39c13defa1d1.png)

The crypto libraries are old and outdated for newer versions of python, so the updated/maintained one is [pycryptodome](https://pypi.org/project/pycryptodome/). But if you have [Crypto](https://pypi.org/project/crypto/) already installed then it will interfere with pycryptodome. so open cmd and type
```sh-session
$ pip uninstall -y crypto
$ pip install --force-reinstall pycryptodome
...
```

**Comment by Rdimo** [comment]
> i get similar on line 20 ![image](https://user-images.githubusercontent.com/90978198/169846390-91d07e4e-f0ea-4c58-9b41-06e7cfa580e6.png)

regarding your issue, pypiwin32 install incorrectly so either try reinstalling it (`pip install --force-reinstall pypiwin32`) or if that doesn't solve it try reinstalling python and installing the reqs again. Try googling a solution too

**Comment by addi00000** [comment]
> i get similar on line 20 ![image](https://user-images.githubusercontent.com/90978198/169846390-91d07e4e-f0ea-4c58-9b41-06e7cfa580e6.png)

may need to be installed in elevated command prompt if installation issue persists
