### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lightaria2** [Rdimo/Hazard-Token-Grabber-V2#326]
why everytime i try to send my friend for testing its not working but work perfect fine with me doing it...i try several token grabber but also end up the same...my friend click the exe but there is no token coming to my server

**Comment by Francesco2426** [comment]
thats scummy to token log your friends lmao

**Comment by lightaria2** [comment]
> thats scummy to token log your friends lmao

i got his permission we both testing it out so i was wodering why it doesnt work when he run the EXE

**Comment by Rdimo** [comment]
> > thats scummy to token log your friends lmao
> 
> i got his permission we both testing it out so i was wodering why it doesnt work when he run the EXE

its most likely because of both of your operating systems are different, or just different versions,
Hazardv2 only supports win10 + win11 which might be why it worked for you but not for him. Could also be because of other factors but I suspect its most likely this
