### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by saudaalseri** [Rdimo/Hazard-Token-Grabber-V2#327]
![Screenshot 2022-05-25 023156](https://user-images.githubusercontent.com/82798415/170148385-2d6e56af-e45e-4062-99fa-61578586d6eb.png)

**Comment by splitparadcx** [comment]
happened to me too don't know what to do

**Comment by splitparadcx** [comment]
You have to install python on the microsoft store, then use the pip command

**Comment by Rdimo** [comment]
#183
