### ISSUE TITLE
Solved!

### ISSUE THREAD

**Issue by CJGitHubCJ** [Rdimo/Hazard-Token-Grabber-V2#328]

**Comment by CJGitHubCJ** [comment]
file "main.py" line 3 in <Module>

**Comment by CJGitHubCJ** [comment]
Happens when running the .exe file

**Comment by CJGitHubCJ** [comment]
I run pip install httpx, it says the following: no matching distribution found for httpx

**Comment by CJGitHubCJ** [comment]
I also ran python -m pip install httpx, still not a recognised module

**Comment by Rdimo** [comment]
👍
