### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Spinyyy** [Rdimo/Hazard-Token-Grabber-V2#329]
![help](https://user-images.githubusercontent.com/70394401/170250678-25a63001-f97c-4905-b07c-8853039742b4.png)

**Comment by GarudaID** [comment]
> ![help](https://user-images.githubusercontent.com/70394401/170250678-25a63001-f97c-4905-b07c-8853039742b4.png)

install module 'httpx' on ur computer, visit this website for more information https://www.python-httpx.org/ 
or type this in cmd 

`pip install httpx`

**Comment by EnderGod11** [comment]
Make sure you're using the real python, not microsoft python.

**Comment by Rdimo** [comment]
#241
