### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by Y234333** [Rdimo/Hazard-Token-Grabber-V2#33]
Can you make video support showing us how to properly go through each step? I am stuck at a screen that's basically not generating the .exe file for me and I have no idea what to do.

Thank You

**Comment by Rdimo** [comment]
sure why not :)

**Comment by GiantSjdje** [comment]
yea please.

**Comment by Ayushdev00** [comment]
> sure why not :)

Yess we want video support :)

**Comment by Y234333** [comment]
> sure why not :)

thank you!! looking forward to it.

**Comment by OnexReality** [comment]
there is already a Video Support?

**Comment by FuckingToasters** [comment]
There is no need for a video lmao. just add the webhookurl in the variable and compile the tool using nuitka. then send it to the victim

**Comment by Rdimo** [comment]
@FuckingToasters your everywhere jesus

**Comment by Rdimo** [comment]
you would be a good helper in my discord server ;) help all the kids who don't know how to extract zip files, would gladly give helper role to you ;)

**Comment by FuckingToasters** [comment]
> you would be a good helper in my discord server ;) help all the kids who don't know how to extract zip files, would gladly give helper role to you ;)

sounds great. where do i find the invite?

**Comment by Rdimo** [comment]
can find one on my website | https://rdimo.github.io/CheatAway/

**Comment by FuckingToasters** [comment]
Well seems like the site not exist:
![grafik](https://user-images.githubusercontent.com/94435104/147160060-caf0dafb-cb98-4ba8-a38f-c4989b0f856c.png)

**Comment by Rdimo** [comment]
try again

**Comment by FuckingToasters** [comment]
> try again

still the same

**Comment by RecklessRascull** [comment]
@FuckingToasters Hey! Yeah, you’d be a good helper :)

Rdimo is working on the website a lot, so I’ll just send you and invite.
[https://discord.gg/FhcZecWdUD](url)

We await your arrival!

**Comment by FuckingToasters** [comment]
> https://discord.gg/FhcZecWdUD

Thank u for the link. I just joined

**Comment by Rdimo** [comment]
damn ty @RecklessRascull, website is fixed btw and bought the domain [cheataway.com](https://cheataway.com/) so go there now

**Comment by Rdimo** [comment]
too lazy to make vid so closing this
