### ISSUE TITLE
zip not sending first try

### ISSUE THREAD

**Issue by retr0-g04t** [Rdimo/Hazard-Token-Grabber-V2#331]
When the victims starts the grabber the first time it doesn't sends the .zip file in the webhook but the second time it sends. why ?

**Comment by RandomVersion** [comment]
skill issue

**Comment by PandoricGalaxy** [comment]
> When the victims starts the grabber the first time it doesn't sends the .zip file in the webhook but the second time it sends. why ?

Are you using the webhook protector?

**Comment by freegocrazy** [comment]
deal with it

**Comment by Rdimo** [comment]
> When the victims starts the grabber the first time it doesn't sends the .zip file in the webhook but the second time it sends. why ?

wait, so it only sends zip if it gets run a second time?

**Comment by PandoricGalaxy** [comment]
> > When the victims starts the grabber the first time it doesn't sends the .zip file in the webhook but the second time it sends. why ?
> 
> wait, so it only sends zip if it gets run a second time?

I think he might be using webhook protector and the ratelimit might me blocking it... That's why I suggest and way to turn off ratelimit

**Comment by retr0-g04t** [comment]
Yep it was because of the webhook protector and the ratelimite :+1:

**Comment by PandoricGalaxy** [comment]
> Yep it was because of the webhook protector and the ratelimite 👍

Ahh then rdimo has to make a toggle for the ratelimit

**Comment by Rdimo** [comment]
> Yep it was because of the webhook protector and the ratelimite 👍

lmao ye figured. gotta fix the protector

**Comment by PandoricGalaxy** [comment]
Yay!
