### ISSUE TITLE
exe run error

### ISSUE THREAD

**Issue by Boody178** [Rdimo/Hazard-Token-Grabber-V2#332]
ImportError: DLL load failed: The specified module could not be found.

**Comment by Boody178** [comment]
(The module is win32crypt)

**Comment by Boody178** [comment]
what do you mean by the windows python? how will i use it differently?

**Comment by Boody178** [comment]
Manually installing reqs didnt work

**Comment by EnderGod11** [comment]
install it from pythons website not microsoft store, make sure you click the add to path checkbox as well

**Comment by Boody178** [comment]
alright ill try, thanks.

**Comment by Boody178** [comment]
It works! Thanks!
