### ISSUE TITLE
question

### ISSUE THREAD

**Issue by thatshowpoppin** [Rdimo/Hazard-Token-Grabber-V2#333]
can i add this grabber to a program like spoofer, etc? or any idea how i can make it not so obvious? can I hide the fact that it's a grabber?

**Comment by freegocrazy** [comment]
this software is educational use only, do not use this software to grab anybodys token without permission

**Comment by PandoricGalaxy** [comment]
> can i add this grabber to a program like spoofer, etc? or any idea how i can make it not so obvious? can I hide the fact that it's a grabber?

ofc u can bind it to any program u want.

To make it less obvious u can use obfuscators to obfuscate the code then compile it to exe then bind it to something!
I compiled it directly to exe and got 1 detection on virustotal and its still the same!

**Comment by Rdimo** [comment]
ye ^^
