### ISSUE TITLE
[Not a issue it's just a question] How do i remove the startup ?

### ISSUE THREAD

**Issue by XxDarknedxX** [Rdimo/Hazard-Token-Grabber-V2#337]
So i builded the and it worked as well but it added on startup and now i'm fucked up since there's also people in my server, i have many logs and i don't wanna restart my whole pc because i will lose many files and at same time i can't delete my channel because i have many logs, i noticed it also adds a code to registry which means i'm fucked up now, is there any way to remove it from startup without deleting my webhook or restarting my pc ? Thanks 🙏🙏🙏

**Comment by Resisst** [comment]
I don't see where it makes a registry key to add to startup however you can do this to remove it from the startupdir:

Press Windows + R
Type `shell:startup` and press enter
Make sure that view hidden items is enabled
Delete the file from the directory.

**Comment by XxDarknedxX** [comment]
> I don't see where it makes a registry key to add to startup however you can do this to remove it from the startupdir:
> 
> Press Windows + R Type `shell:startup` and press enter Make sure that view hidden items is enabled Delete the file from the directory.

Yep i found it, i just deleted now, it doesn't excute on startup anymore, thanks i appreciate your help a lot!
