### ISSUE TITLE
No module named 'httpx'

### ISSUE THREAD

**Issue by FunnyMan111** [Rdimo/Hazard-Token-Grabber-V2#340]
When attempting to run the grabber it gives me this error and doesnt send anything to the webhook

Traceback (most recent call last):
  File "main.py", line 3, in <module>
ModuleNotFoundError: No module named 'httpx'

**Comment by FunnyMan111** [comment]
update: i did pip install httpx then the same error showed but httpx was replaced with psutil so i did pip install psutil and now its showing this error

Traceback (most recent call last):
  File "main.py", line 15, in <module>
ModuleNotFoundError: No module named 'PIL'

**Comment by EnderGod11** [comment]
just manually install requirements.txt

**Comment by FunnyMan111** [comment]
oh yeah done that now thx i guess my shitty vpn was blocking it for some reason

**Comment by FunnyMan111** [comment]
how do i remove the file from my discord files now

**Comment by addi00000** [comment]
Reinstall discord is the easiest way to remove injector

**Comment by Rdimo** [comment]
#241
