### ISSUE TITLE
nothing gets sent to the webhook when you open it

### ISSUE THREAD

**Issue by tanukieggs** [Rdimo/Hazard-Token-Grabber-V2#342]
so basically, I compiled it and opened the exe and nun happened, video below of exactly what i did

https://cdn.discordapp.com/attachments/979263575564615684/980980586892132402/unknown_2022.05.30-19.39_1_Trim.mp4

**Comment by Rdimo** [comment]
right so from what I'm seeing is that you have an old ass version of it, like old old old version. Update it and it will work just fine

**Comment by Rdimo** [comment]
> 

read the readme
