### ISSUE TITLE
Issue with file launch

### ISSUE THREAD

**Issue by GunnersRage** [Rdimo/Hazard-Token-Grabber-V2#343]
When opening created file (tested with setup and cmd) 2 cmd windows flash and close and nothing is sent to discord server. 
Things tried:
Tried new webhook and does the same thing.
Made sure correct webhook used (visual check on address line)
re-downloaded files every test (tests from scratch)
tested creating exe with both setup and through cmd
tried using build option
ran file with admin clearance

Packages seem to be downloading and the file is created with no error, however, the file created seems to be bugging out.
Discord on tested account also does not close, making me believe that the file just is closing out instead of running.
If video needs to be sent will send one

**Comment by GunnersRage** [comment]
Running on 32bit windows with python 3.9 (32bit)

**Comment by euclidsss** [comment]
its because your on a 32-bit system. please upgrade to 64-bit or if windows is too slow on 64-bit, migrate to linux. linux isnt as hard as everyone says.

**Comment by GunnersRage** [comment]
Ok got it thank you for letting me know
