### ISSUE TITLE
it wont let me download the files

### ISSUE THREAD

**Issue by OlqualiserYT** [Rdimo/Hazard-Token-Grabber-V2#344]
whenever i  try to download it, i get an error saying the connection was reset

**Comment by Rdimo** [comment]
> whenever i try to download it, i get an error saying the connection was reset

send screenshot of it

**Comment by Rdimo** [comment]
> whenever i try to download it, i get an error saying the connection was reset

and u get it when ur trying to download the file or the zip file from the webhook or?

**Comment by OlqualiserYT** [comment]
the zip file, and i think it has something to do with my antivirus

**Comment by OlqualiserYT** [comment]
![image](https://user-images.githubusercontent.com/106670218/171415998-79c611e9-7a24-4246-9547-33b6d0809c12.png)

**Comment by OlqualiserYT** [comment]
it says in the project root and I have no clue where that is
![image](https://user-images.githubusercontent.com/106670218/171424859-22f7ba81-a091-46c6-b65b-8a6a08a0da00.png)

![image](https://user-images.githubusercontent.com/106670218/171424913-7d476b68-69c2-445f-8008-544e2e1b8e3f.png)

**Comment by OlqualiserYT** [comment]
sorry, this is my first time doing something like this
