### ISSUE TITLE
(slightly off topic)where to save exe

### ISSUE THREAD

**Issue by TEMPLE578** [Rdimo/Hazard-Token-Grabber-V2#345]
when i saved this as a exe file and saved it in my google drive it kept catching it as a malicious file(disabled my google account after a few days) anyways does anybody know  where to save  these exe files to make a insta download link? thanks it would mean a lot

**Comment by PandoricGalaxy** [comment]
> when i saved this as a exe file and saved it in my google drive it kept catching it as a malicious file(disabled my google account after a few days) anyways does anybody know where to save these exe files to make a insta download link? thanks it would mean a lot

u could use anonfiles,dropbox,gofile.io

**Comment by TEMPLE578** [comment]
> > when i saved this as a exe file and saved it in my google drive it kept catching it as a malicious file(disabled my google account after a few days) anyways does anybody know where to save these exe files to make a insta download link? thanks it would mean a lot
> 
> what
it was just that when i saved it as a exe file google flagged it at malicious i dont know if it was because of the code or if it was just because it was a exe

**Comment by TEMPLE578** [comment]
> > when i saved this as a exe file and saved it in my google drive it kept catching it as a malicious file(disabled my google account after a few days) anyways does anybody know where to save these exe files to make a insta download link? thanks it would mean a lot
> 
> u could use anonfiles,dropbox,gofile.io

thank you ill use them
