### ISSUE TITLE
How to test the exe on a virtual machine?

### ISSUE THREAD

**Issue by Anonymoussssssy** [Rdimo/Hazard-Token-Grabber-V2#346]
When I test this on a virtual machine the exe just quits and does nothing, I want it to act normal. How? 

Thank you.

**Comment by euclidsss** [comment]
didnt set it up right then

**Comment by Anonymoussssssy** [comment]
It was setup right, the hazard token grabber is setup for anti vm and anti sandbox that's why it doesn't work

**Comment by Rdimo** [comment]
> It was setup right, the hazard token grabber is setup for anti vm and anti sandbox that's why it doesn't work

yes, you can just turn it off in the config
