### ISSUE TITLE
roblox info all invalid

### ISSUE THREAD

**Issue by Rdmo1** [Rdimo/Hazard-Token-Grabber-V2#347]

**Comment by euclidsss** [comment]
this grabs roblox cookies from roblox studio so his cookie has changed since they logged into studio. not rdimos fault.

**Comment by Rdimo** [comment]
one thing too is that it doesn't check if the roblox cookies are valid or not, which might lead to it just grabbing all outdated cookies. I'm not making it check if its valid just because I don't want it to spend too much time checking
