### ISSUE TITLE
Add ( Steal all passwords of all browsers )

### ISSUE THREAD

**Issue by piano-Bot-music** [Rdimo/Hazard-Token-Grabber-V2#348]
Currently Hazard-Grabber only supports Chrome browser, there are many people who do not use this browser ...
 So it's better to have Hazard-Grabber support for all browsers to steal passwords.

**Comment by euclidsss** [comment]
Like he says in the description, hes not making it anymore op. add it yourself.

**Comment by Rdimo** [comment]
#314
