### ISSUE TITLE
Help With loginvault.db file gen

### ISSUE THREAD

**Issue by danmoussa123** [Rdimo/Hazard-Token-Grabber-V2#351]
Okay I'm sure this is a noob ? but can someone tell me what that file is when the program is ran, and how can I use that file.

**Comment by Rdimo** [comment]
> Okay I'm sure this is a noob ? but can someone tell me what that file is when the program is ran, and how can I use that file.

what

**Comment by dekrypted** [comment]
> Okay I'm sure this is a noob ? but can someone tell me what that file is when the program is ran, and how can I use that file.

Hello!
loginvault.db is not meant to be used by you.

It simply copies all the passwords/cookies from chrome!
Only issue being that it's impossible for a human to read it.
So, Hazard Stealer v2 extracts all the passwords from the database files and decrypts them for you!
So there is no need to use the files. All the passwords and cookies from them are in the Passwords and Cookies files.

Hope this helps!

@danmoussa123
