### ISSUE TITLE
Can this be Crypted?

### ISSUE THREAD

**Issue by garethblockchain** [Rdimo/Hazard-Token-Grabber-V2#353]
I'm not familiar with python. Can it be made FUD using a 3rd party application?

**Comment by Rdimo** [comment]
> I'm not familiar with python. Can it be made FUD using a 3rd party application?

ofc it can be fud. Can be made fud with a 3rd party application too but that obviously depends on what application it is

**Comment by PandoricGalaxy** [comment]
https://github.com/Rdimo/Hazard-Token-Grabber-V2/issues/359#issuecomment-1147790350
