### ISSUE TITLE
unsuported 16-bit application

### ISSUE THREAD

**Issue by V4pe** [Rdimo/Hazard-Token-Grabber-V2#355]
unsuported 16-bit application
This version is not compatible with the Windows you're running

**Comment by addi00000** [comment]
What version of windows are you running?

**Comment by V4pe** [comment]
11

**Comment by V4pe** [comment]
windows 11

**Comment by V4pe** [comment]
fuck you u fucking cunt

**Comment by V4pe** [comment]
nigga 💀

**Comment by addi00000** [comment]
> fuck you u fucking cunt

What did I do

**Comment by addi00000** [comment]
:(

**Comment by PandoricGalaxy** [comment]
Close the issue

**Comment by dekrypted** [comment]
How bout you close the issue?

**Comment by PandoricGalaxy** [comment]
> How bout you close the issue?

I can't cause I didn't open.... That's why I told u to

**Comment by V4pe** [comment]
Nvm it works lmfao
