### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Manhajus-Salafiyyah** [Rdimo/Hazard-Token-Grabber-V2#359]
Well, I have been trying to get it on kali linux, while i do have it on windows, however I just wanted to try it out on windows. Will it work and if so how? I have tried doing it for a bit of time, but now i dont know if it will work and I need a bit of help in doing it. 

EDIT: It works perfectly on windows, but i want to use veil on kali linux and other stuff to create a backdoor and try and make it undetectable by an AV. I have been trying to learn hacking, and i thought well this would be a cool little project to work on however I am in early stages and maybe i might create programs hopefully some day!

**Comment by PandoricGalaxy** [comment]
How will u use veil on hazard? Its for backdoors isn't it so how will u use it on hazard grabber? Also simply obfuscating the py code will make it fud on vt (it's fud so no problems uploading there) but the problem is converting it to exe. That flags it so u need to find a way to convert it to exe without flag. Using even simple obfuscators work to make the python file fud I dont think u need veil

**Comment by Rdimo** [comment]
> How will u use veil on hazard? Its for backdoors isn't it so how will u use it on hazard grabber? Also simply obfuscating the py code will make it fud on vt (it's fud so no problems uploading there) but the problem is converting it to exe. That flags it so u need to find a way to convert it to exe without flag. Using even simple obfuscators work to make the python file fud I dont think u need veil

issue with encrypting it is that it will only be undetected for like 1-2 days

**Comment by Rdimo** [comment]
> > How will u use veil on hazard? Its for backdoors isn't it so how will u use it on hazard grabber? Also simply obfuscating the py code will make it fud on vt (it's fud so no problems uploading there) but the problem is converting it to exe. That flags it so u need to find a way to convert it to exe without flag. Using even simple obfuscators work to make the python file fud I dont think u need veil
> 
> issue with obfuscating it is that it will only be undetected for like 1-2 days

**Comment by PandoricGalaxy** [comment]
> > How will u use veil on hazard? Its for backdoors isn't it so how will u use it on hazard grabber? Also simply obfuscating the py code will make it fud on vt (it's fud so no problems uploading there) but the problem is converting it to exe. That flags it so u need to find a way to convert it to exe without flag. Using even simple obfuscators work to make the python file fud I dont think u need veil
> 
> issue with obfuscating it is that it will only be undetected for like 1-2 days

+ Just giving the .py is not the best so need to convert it to .exe which adds detections

**Comment by xylo101** [comment]
W grabber

**Comment by euclidsss** [comment]
kali :clown_face:
