### ISSUE TITLE
it wont work

### ISSUE THREAD

**Issue by xylo101** [Rdimo/Hazard-Token-Grabber-V2#368]
i tried everything but it wont send the info to the webhook i dont understand i tried 3 different webhooks i even tried the original hazard nuker

**Comment by Rdimo** [comment]
> i tried everything but it wont send the info to the webhook i dont understand i tried 3 different webhooks i even tried the original hazard nuker

right, trying different webhooks wont solve it. The error is in how you setup that grabber, please tell me how and what you did

**Comment by HermesTrismegistus13** [comment]
when i double click the bat file nothing runs and a window opens up saying type exe name i write token graber as u said but it sows that
![image](https://user-images.githubusercontent.com/96198400/173165735-09a2d1b1-f6a2-4d56-9b11-01aff9ea3d63.png)

**Comment by Rdimo** [comment]
#183
