### ISSUE TITLE
I can't build the EXE

### ISSUE THREAD

**Issue by Aranfiy** [Rdimo/Hazard-Token-Grabber-V2#369]
Enter the exe name : vc

Name is: vc
'PyInstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find C:\Users\Kage\Desktop\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\vc.spec

generated exe as vc.exe in the dist folder

Press any key to continue . . .

**Comment by elmoelmo1** [comment]
you didnt need to make a issue

**Comment by Aranfiy** [comment]
> you didnt need to make a issue

is there a solution? i tried finding one

**Comment by Rdimo** [comment]
#183
