### ISSUE TITLE
New Token Encryption

### ISSUE THREAD

**Issue by omnituensaeternum** [Rdimo/Hazard-Token-Grabber-V2#370]
See https://github.com/NobodyWouldEverUseThis7/Token-encryption-writeup to improve your implementation.

**Comment by Rdimo** [comment]
> See https://github.com/NobodyWouldEverUseThis7/Token-encryption-writeup to improve your implementation.

this grabber was the first grabber to grab encrypted tokens, the regex they use and such is the first decryptor I made for hazard v2

**Comment by omnituensaeternum** [comment]
You spastic fuck you stole the og code from Clara.

**Comment by Rdimo** [comment]
> You spastic fuck you stole the og code from Clara.

who tf is Clara, lmao didn't steal the code from anyone 💀

**Comment by Rdimo** [comment]
stop going around and making issues at every repo there is 💀💀
the code in the readme is ass and regex can drastically be improved
![image](https://user-images.githubusercontent.com/80375661/173181065-2a49c764-4339-4bc6-8fba-9fd57eccb92b.png)

**Comment by omnituensaeternum** [comment]
Shutup skid

**Comment by Rdimo** [comment]
> Shutup skid

don't need another description of yourself,
