### ISSUE TITLE
'Unhandled exception in script'

### ISSUE THREAD

**Issue by Snipeeeey** [Rdimo/Hazard-Token-Grabber-V2#386]
Keep getting this error after trying to run the grabber by myself. 
I re-installed the requirements, but that didn't work, any solutions.

![image](https://user-images.githubusercontent.com/73399792/173877450-c298da95-99e9-4f90-83ff-2105d0618aa4.png)

**Comment by kaisenlmao** [comment]
same

**Comment by Rdimo** [comment]
> Keep getting this error after trying to run the grabber by myself. I re-installed the requirements, but that didn't work, any solutions.
> 
> ![image](https://user-images.githubusercontent.com/73399792/173877450-c298da95-99e9-4f90-83ff-2105d0618aa4.png)

fixing it rn, ty for reporting
