### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by StopTheCap-fr** [Rdimo/Hazard-Token-Grabber-V2#387]
Does the grabber not work on vms?

**Comment by addi00000** [comment]
usually not unless you set it up very realistically with drivers and high specs

**Comment by addi00000** [comment]
![image](https://user-images.githubusercontent.com/81730200/174101673-59a16e89-3164-40fc-9bba-1eb7409b957e.png)

**Comment by Rdimo** [comment]
> Does the grabber not work on vms?

you can turn it off in the config so it can run in vms if you want
