### ISSUE TITLE
lmfao

### ISSUE THREAD

**Issue by glosifyed** [Rdimo/Hazard-Token-Grabber-V2#389]
ur "injection" is a dualhook, please don't fall for these scams
If you have proof its not a dualhook, please comment it below :)

**Comment by addi00000** [comment]
prove it pls

**Comment by Rdimo** [comment]
> ur "injection" is a dualhook, please don't fall for these scams If you have proof its not a dualhook, please comment it below :)

the injection is open source, physically can't be dual hooked without anyone knowing, if you're talking about the injection that is obfuscated then just use the one that isn't obfuscated or http debug the obfuscated one to see if its dualhooked or not. Having my server getting spammed is the last things im looking for
