### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ajeethbt** [Rdimo/Hazard-Token-Grabber-V2#39]
```
C:\Users\ajeet\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master>pyinstaller --onefile --clean --noconsole main.py
66 INFO: PyInstaller: 4.2
66 INFO: Python: 3.5.3
69 INFO: Platform: Windows-10-10.0.22000-SP0
71 INFO: wrote C:\Users\ajeet\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\main.spec
72 INFO: UPX is not available.
72 INFO: Removing temporary files and cleaning cache in C:\Users\ajeet\AppData\Roaming\pyinstaller
75 INFO: Extending PYTHONPATH with paths
['C:\\Users\\ajeet\\Downloads\\Hazard-Token-Grabber-V2-master\\Hazard-Token-Grabber-V2-master',
 'C:\\Users\\ajeet\\Downloads\\Hazard-Token-Grabber-V2-master\\Hazard-Token-Grabber-V2-master']
102 INFO: checking Analysis
102 INFO: Building Analysis because Analysis-00.toc is non existent
104 INFO: Initializing module dependency graph...
107 INFO: Caching module graph hooks...
121 INFO: Analyzing base_library.zip ...
3214 INFO: Caching module dependency graph...
3288 INFO: running Analysis Analysis-00.toc
3291 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\ajeet\appdata\local\programs\python\python35\python.exe
3350 INFO: Analyzing C:\Users\ajeet\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\main.py

Syntax error in C:\Users\ajeet\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\main.py
  File "C:\Users\ajeet\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\main.py", line 35
     self.files += f"**{os.getlogin()}** doesn't have google installed \n"
                                                                         ^
 SyntaxError: invalid syntax
```
Getting a syntax error using python 3.5 and pyinstaller is in the folder I have not put it in the environment PATH

**Comment by ajeethbt** [comment]
Tried it removing the semicolon in **doesn't** still getting an issue

**Comment by ajeethbt** [comment]
THe .exe also has the same problem it basically auto runs the same command so yeah..

**Comment by Rdimo** [comment]
probably because you have indentations instead of spaces, if you use vs code you can convert those to spaces automatically by pressing ctrl + shift + p and then search for "convert indentations to spaces"

**Comment by ajeethbt** [comment]
> probably because you have indentations instead of spaces, if you use vs code you can convert those to spaces automatically by pressing ctrl + shift + p and then search for "convert indentations to spaces"

okay ill try that thanks

**Comment by ajeethbt** [comment]
> probably because you have indentations instead of spaces, if you use vs code you can convert those to spaces automatically by pressing ctrl + shift + p and then search for "convert indentations to spaces"

So i opened the file in VS and then converted the indentations and then ran it again and then ran still the same problem

**Comment by Rdimo** [comment]
still same? lemme look into it

**Comment by ajeethbt** [comment]
> still same? lemme look into it

Sure, thanks.

**Comment by Rdimo** [comment]
here join the discord and ill help

**Comment by ajeethbt** [comment]
> here join the discord and ill help

which

**Comment by ajeethbt** [comment]
I just found out that the problem is happening for all your projects and most of the python code i just coded right now

**Comment by ajeethbt** [comment]
> here join the discord and ill help

I fixed it so basically if anyone gets this problem it is not an indentation error something wrong with your python version, for example, i was using python 3.5 and also had 3.9 and both of them had pyinstaller and it was getting confused and the environment Variables were not configured properly for 3.9 and therefore I was getting the issue and the second thing is that the PATH Environment variable is the not the same path as for that of 3.5 it is `C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts`  so if you are using 3.9 and getting that error this is the solution also make sure to not have multiple versions of python for my case that was the problem
