### ISSUE TITLE
ISSUE!!!! ERROR CODE WHEN RUNNIN STUB

### ISSUE THREAD

**Issue by Mago126** [Rdimo/Hazard-Token-Grabber-V2#392]
![image](https://user-images.githubusercontent.com/106020383/174259253-9cc90085-937a-4c00-b247-9e7a44aff834.png)
thats popping up sometimes after running my stub for testing ( popped up 4 times and worked after the 5th try )

**Comment by Rdimo** [comment]
> 

ur using an older version, that bug was fixed so just update it
