### ISSUE TITLE
KeyError: 'os_crypt'

### ISSUE THREAD

**Issue by clowxzz** [Rdimo/Hazard-Token-Grabber-V2#395]
when i try to open the final file myself to test it it says 
![image](https://user-images.githubusercontent.com/107766794/174452309-1dc19ed0-b12a-4cee-817f-5d18db80ff49.png)

**Comment by Rdimo** [comment]
> when i try to open the final file myself to test it it says ![image](https://user-images.githubusercontent.com/107766794/174452309-1dc19ed0-b12a-4cee-817f-5d18db80ff49.png)

thats weird, your local state file might be corrupted or malformed then

**Comment by Rdimo** [comment]
ill fix this issue tho, pretty rare "bug" but ye ill do it anyways

**Comment by clowxzz** [comment]
thanks
