### ISSUE TITLE
Suggestion to fix one of the cons

### ISSUE THREAD

**Issue by Dodeedoo** [Rdimo/Hazard-Token-Grabber-V2#398]
"Python is an interpreted language, it needs to pack the engine & all dependencies in the binary making the **file size very big**"

Instead of having the victim install the compiled exe which is a large file, have them install a much smaller exe that'll install the actual malware on its own.

victim install smaller file -> smaller file downloads bigger file -> yay

**Comment by ilylunar** [comment]
> "Python is an interpreted language, it needs to pack the engine & all dependencies in the binary making the **file size very big**"
> 
> Instead of having the victim install the compiled exe which is a large file, have them install a much smaller exe that'll install the actual malware on its own.
> 
> victim install smaller file -> smaller file downloads bigger file -> yay

Do you mean like the smaller file writes the malware file and then run it?

**Comment by Dodeedoo** [comment]
> > "Python is an interpreted language, it needs to pack the engine & all dependencies in the binary making the **file size very big**"
> > Instead of having the victim install the compiled exe which is a large file, have them install a much smaller exe that'll install the actual malware on its own.
> > victim install smaller file -> smaller file downloads bigger file -> yay
> 
> Do you mean like the smaller file writes the malware file and then run it?

It downloads the file from some site and runs it, yes.

**Comment by Dodeedoo** [comment]
Aw man, it is possible by having someone run a batch file, issue is you can easily edit a batch file + there’s a preview if sent through discord

**Comment by Rdimo** [comment]
> Aw man, it is possible by having someone run a batch file, issue is you can easily edit a batch file + there’s a preview if sent through discord
> 
> I’ll make a fork and see how it goes I guess

yup yup
