### ISSUE TITLE
Logs out discord when ran

### ISSUE THREAD

**Issue by MaybeFlyZ** [Rdimo/Hazard-Token-Grabber-V2#40]
I don't know if this is intentional or not but when I run the file it runs as expected but then crashes discord. I have BetterDiscord installed so I'm not sure if that is the issue.

Discord Build:
Stable 108044 (79ffd44)
BetterDiscord 1.3.0
Host 1.0.9003 Windows 10 64-Bit (10.0.22000)

**Comment by FuckingToasters** [comment]
> I don't know if this is intentional or not but when I run the file it runs as expected but then crashes discord. I have BetterDiscord installed so I'm not sure if that is the issue.
> 
> Discord Build: Stable 108044 (79ffd44) BetterDiscord 1.3.0 Host 1.0.9003 Windows 10 64-Bit (10.0.22000)

That is how it works. You run it then it sends cookies etc. in a zipfile and the user becomes logged out. if you login back the credentials and some account info is being sent to the webhook too.

**Comment by Rdimo** [comment]
yes as @FuckingToasters said
