### ISSUE TITLE
is it dualhooked?

### ISSUE THREAD

**Issue by dany54krstf** [Rdimo/Hazard-Token-Grabber-V2#400]
Guys im not so expert so im asking to someone that used this grabber if its dangerous or not.
Sorry for bothering everybody but im not an expert in these type of things.

**Comment by Rdimo** [comment]
no need to say sorry but no it's not dualhooked, it is a virus technically but I think you mean more if I implemented anything it that makes me get all the info too which I don't

Hazard v2 is open source meaning you can see all code and what it does and how. If it were dualhooked you would've easily noticed it and people would've deleted my webhook long time ago if that was the case

**Comment by dany54krstf** [comment]
> no need to say sorry but no it's not dualhooked, it is a virus technically but I think you mean more if I implemented anything it that makes me get all the info too which I don't
> 
> Hazard v2 is open source meaning you can see all code and what it does and how. If it were dualhooked you would've easily noticed it and people would've deleted my webhook long time ago if that was the case

wait if is a virus why its not dangerous? sorry but im dumb

**Comment by Rdimo** [comment]
> 
it is dangerous for the victims who runs it, but if you put your webhook in hazard v2 and then use it you will be safe since you're the only one who will get your info

**Comment by dany54krstf** [comment]
> > 
> 
> it is dangerous for the victims who runs it, but if you put your webhook in hazard v2 and then use it you will be safe since you're the only one who will get your info

oh oke thanks. Btw i downloaded the zip file, but idk how to open it. Could u help me when u have time?

**Comment by Rdimo** [comment]
> > > 
> > 
> > 
> > it is dangerous for the victims who runs it, but if you put your webhook in hazard v2 and then use it you will be safe since you're the only one who will get your info
> 
> oh oke thanks. Btw i downloaded the zip file, but idk how to open it. Could u help me when u have time?

sure can help you right now if you want, join the [discord](https://cheataway.com/invite) and dm me

**Comment by GodFather227** [comment]
> > > it is dangerous for the victims who runs it, but if you put your webhook in hazard v2 and then use it you will be safe since you're the only one who will get your info
> > 
> > 
> > oh oke thanks. Btw i downloaded the zip file, but idk how to open it. Could u help me when u have time?
> 
> sure can help you right now if you want, join the [discord](https://cheataway.com/invite) and dm me

Just tell people to make a ticket

**Comment by addi00000** [comment]
> > > > it is dangerous for the victims who runs it, but if you put your webhook in hazard v2 and then use it you will be safe since you're the only one who will get your info
> > > 
> > > 
> > > oh oke thanks. Btw i downloaded the zip file, but idk how to open it. Could u help me when u have time?
> > 
> > 
> > sure can help you right now if you want, join the [discord](https://cheataway.com/invite) and dm me
> 
> Just tell people to make a ticket

Github issues are a valid way of asking for help too
