### ISSUE TITLE
Not working on replit

### ISSUE THREAD

**Issue by Newtodicordchad** [Rdimo/Hazard-Token-Grabber-V2#403]
I am trying to run thi program on replit cause ye but it always ends up with error any solution ?

**Comment by Smug246** [comment]
whats the error and why arnt you using it on replit. if possible i'd just use it normally on desktop

**Comment by Newtodicordchad** [comment]
> whats the error and why are you using it on replit. if possible i'd just use it normally on desktop

I am android guy so ye I wanna run this script but unfortunately it ends up with error says @echo command not found in shell and also it takes hell of time to install requirements

**Comment by addi00000** [comment]
> I am trying to run thi program on replit cause ye but it always ends up with error any solution ?

this only works on windows 10/11 desktops

**Comment by Newtodicordchad** [comment]
> > I am trying to run thi program on replit cause ye but it always ends up with error any solution ?
> 
> this only works on windows 10/11 desktops

I mean my exe is ready and I Install every requirements idk if it works or not how can I test it ??

**Comment by Rdimo** [comment]
this is not meant to be run on replit

**Comment by euclidsss** [comment]
> > > I am trying to run thi program on replit cause ye but it always ends up with error any solution ?
> > 
> > 
> > this only works on windows 10/11 desktops
> 
> I mean my exe is ready and I Install every requirements idk if it works or not how can I test it ??

this only works on windows as seen in the source and README 💀
