### ISSUE TITLE
My discord just dies everytime i open it

### ISSUE THREAD

**Issue by Type321** [Rdimo/Hazard-Token-Grabber-V2#404]
after opening the program i have to restart my computer and reinstall discord. is there a setting i have to change in the configs?
This is what i have set already:

    'ping_on_run': False,
    'kill_processes': True,
    'startup': True,
    'hide_self': True,
    'anti_debug': True,

**Comment by Type321** [comment]
never mind im slow im sorry

**Comment by Smug246** [comment]
lmao

**Comment by addi00000** [comment]
> after opening the program i have to restart my computer and reinstall discord. is there a setting i have to change in the configs? This is what i have set already:
> 
> ```
> 'ping_on_run': False,
> 'kill_processes': True,
> 'startup': True,
> 'hide_self': True,
> 'anti_debug': True,
> ```

Set `'kill_processes'` to `False`

**Comment by addi00000** [comment]
or it may be injection interfering

**Comment by Smug246** [comment]
i think he realised smh
