### ISSUE TITLE
import cookie

### ISSUE THREAD

**Issue by DogusCyk** [Rdimo/Hazard-Token-Grabber-V2#407]
Where exactly should I put all the cookies?

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/175632798-83c075ea-cccc-4080-881c-0dad7ab70c37.png)


> > Where exactly should I put all the cookies?
> 
> Cookie of what?

i'm talking about these

**Comment by Rdimo** [comment]
use [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg)
