### ISSUE TITLE
pyinstaller is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by OlqualiserYT** [Rdimo/Hazard-Token-Grabber-V2#409]

**Comment by OlqualiserYT** [comment]
![image](https://user-images.githubusercontent.com/106670218/175663190-92ea00c0-c4dd-4a0b-b947-77dd732e9ede.png)

**Comment by Resisst** [comment]
Deleting system32 should fix it

**Comment by JoarXT** [comment]
just reinstall windows and it should be fixed

**Comment by JanRed321** [comment]
?
