### ISSUE TITLE
Doesn't grab Brave or other browser passwords. 

### ISSUE THREAD

**Issue by MaybeFlyZ** [Rdimo/Hazard-Token-Grabber-V2#41]
I can see in the code that it grabs saved passwords from other browsers however it doesn't output in into the webhook.

**Comment by Rdimo** [comment]
no it only grabs passwords and cookies from google chrome, no other, I can make it grab from 10+ browsers but I don't want to post stealers here that are **that** op, I mostly sell those other ones that grab credit cards, addresses, phone numbers, passwords and all of that
