### ISSUE TITLE
On startup this appears

### ISSUE THREAD

**Issue by Dxstinate** [Rdimo/Hazard-Token-Grabber-V2#412]
![Unhandled exception in script 26 06 2022 13_13_43](https://user-images.githubusercontent.com/108217943/175811516-86b54e7c-a788-4ffe-843b-9d49a0533e38.png)

**Comment by Badafofo** [comment]
install module pip install httpx

**Comment by Rdimo** [comment]
#241

**Comment by Dxstinate** [comment]
![site-packages 26 06 2022 18_27_00 (2)](https://user-images.githubusercontent.com/108217943/175824196-0c6829f9-dd6e-4d57-afcb-fa25210e6263.png)
![Właściwości systemu 26 06 2022 18_27_35](https://user-images.githubusercontent.com/108217943/175824197-d66050ea-d7fc-454c-a7ec-cbc20d70c51c.png)
i did both of those and it still doesn't work

**Comment by Dxstinate** [comment]
nvm i just had to reinstall it
