### ISSUE TITLE
how too add python too the path

### ISSUE THREAD

**Issue by Alansian** [Rdimo/Hazard-Token-Grabber-V2#415]
i need help on how too add pyhton too the path

**Comment by GodFather227** [comment]
> i need help on how too add pyhton too the path

You dumbass hoe google how to do it shit takes like 10 seconds god damn

**Comment by Alansian** [comment]
i did and when i downloaded python it just dosnt work can u add me on discord too help me? sapnu puas#6969

**Comment by GodFather227** [comment]
> > > i need help on how too add pyhton too the path
> > 
> > 
> > You dumbass hoe google how to do it shit takes like 10 seconds god damn
> 
> mad kid, you shouldn't insult him but just help, net everyone have to know what you do
> 
> So Alansian try doing what that site says: https://datatofish.com/add-python-to-windows-path/

Who?
