### ISSUE TITLE
ERROR CDODE? WHEN RUNNING STUB??

### ISSUE THREAD

**Issue by Mago126** [Rdimo/Hazard-Token-Grabber-V2#421]
![image](https://user-images.githubusercontent.com/106020383/176944859-10c0b400-68b6-4df3-99c7-72cda0f5ade4.png)
WTFFFFFFF

**Comment by GodFather227** [comment]
Send the whole error dumb fuck

**Comment by Resisst** [comment]
calm the fuck down mate

**Comment by GodFather227** [comment]
I’m calm as shit my nigga

**Comment by Mago126** [comment]
maybe that error code came because i was using the old version im using the new version now

**Comment by Rdimo** [comment]
> maybe that error code came because i was using the old version im using the new version now

and it works?

**Comment by Mago126** [comment]
> > maybe that error code came because i was using the old version im using the new version now
> 
> and it works?

yes it works it was just because i was using an older version 8 days ago

**Comment by Rdimo** [comment]
ah alr
