### ISSUE TITLE
Where do i find setup.bat?

### ISSUE THREAD

**Issue by OscarPlayzYT0** [Rdimo/Hazard-Token-Grabber-V2#422]
Where do i double click the setup.bat need help downloading this, if anyone can help leave a comment here or dm me on discord OscarPlayz#1839

**Comment by Rdimo** [comment]
you do it where you downloaded the file, where else

**Comment by GodFather227** [comment]
> Where do i double click the setup.bat need help downloading this, if anyone can help leave a comment here or dm me on discord OscarPlayz#1839

Just redownload bruh

**Comment by euclidssss** [comment]
> Where do i double click the setup.bat need help downloading this, if anyone can help leave a comment here or dm me on discord OscarPlayz#1839

goofy ass username :skull: :skull:
