### ISSUE TITLE
module not found httpx

### ISSUE THREAD

**Issue by akargokay4** [Rdimo/Hazard-Token-Grabber-V2#429]
![dsdsddssdd](https://user-images.githubusercontent.com/98610770/177323796-6af39d38-37c5-4703-936d-24592e67bff2.PNG)

how can i solve this problem ?

**Comment by akargokay4** [comment]
it says PIL right now and tried to pip install PIL but im getting error

**Comment by 0x3C50** [comment]
> it says PIL right now and tried to pip install PIL but im getting error

pip install -U Pillow

**Comment by akargokay4** [comment]
ModuleNotFoundError: No module named 'Crypto'

**Comment by 0x3C50** [comment]
> ModuleNotFoundError: No module named 'Crypto'

`pip uninstall crypto pycrypto pycryptodome` and `pip install -U pycryptodome`

**Comment by akargokay4** [comment]
i installed all of the requirements and there is no error when i run it. And still the token is not being showed on webhook

**Comment by akargokay4** [comment]
how many minutes

**Comment by akargokay4** [comment]
it doesnt work

**Comment by akargokay4** [comment]
pls help me

**Comment by akargokay4** [comment]
can you help me on discord ?

**Comment by GodFather227** [comment]
> can you help me on discord ?

Install the reqs tard nugget
