### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by akargokay4** [Rdimo/Hazard-Token-Grabber-V2#430]
I installed all of the requirements but it is still not working

**Comment by GodFather227** [comment]
Send error

**Comment by akargokay4** [comment]
there is no error but i can send a screenshot 1sec

**Comment by GodFather227** [comment]
> ![dddddddddd](https://user-images.githubusercontent.com/98610770/177335782-6a85e62e-de8e-40bc-8b1d-3ecbd2d57b92.PNG)

Did you even put your webhook in?

**Comment by akargokay4** [comment]
yes surely

**Comment by GodFather227** [comment]
> yes surely

Join the server and we can join vc when I’m off

**Comment by GodFather227** [comment]
I’m guessing it’s something small that we’re missing over

**Comment by akargokay4** [comment]
you mean Cheataway discord server ?

**Comment by akargokay4** [comment]
you can add me on discord GOKO#3169 if you want

**Comment by GodFather227** [comment]
> you mean Cheataway discord server ?

Yuh

**Comment by akargokay4** [comment]
what is your nickname on discord ?

**Comment by Rdimo** [comment]
ur not trying to run it as a python script right?

**Comment by akargokay4** [comment]
im running it on a virtual machine. The older version of hazard grabber is working on virtual machine.

**Comment by Rdimo** [comment]
so you just downloaded this and didnt even know what it did and proceeded to run it on a vm which then lead to the antivm make hazard exit and you thought it didn't work?

**Comment by FuckingToasters** [comment]
> it shows restart shell error

r u kidding me? you said it shows a erro and when someone asked what the error is you said there isn't any error at all. oh boy....
