### ISSUE TITLE
Can anyone help me on this issue, Traceback (most recent call last):   File "main.py", line 4, in <module> ModuleNotFoundError: No module named 'httpx'

### ISSUE THREAD

**Issue by DarkSuffer01** [Rdimo/Hazard-Token-Grabber-V2#434]
Error:
Traceback (most recent call last):
  File "main.py", line 4, in <module>
ModuleNotFoundError: No module named 'httpx'

I tried figuring this out a couple mins, I installed all of the requirements. Still doesn't work.
Is it patched or what.
![problem](https://user-images.githubusercontent.com/107288467/177488482-9845d49e-cefd-474a-aa6a-3048d22d6c73.jpg)

**Comment by Rdimo** [comment]
#357

**Comment by DarkSuffer01** [comment]
> You seem like a weird skid but ok lemme explain it to ya:
> 
> the httpx module is a better request libary which isn't installed by defalut. it you still have the issue after installing the requirements then httpx might not me listed in the requirements file? you can add it there or execute this command `pip install httpx`

I already installed "pip install httpx" Still didn't work.
