### ISSUE TITLE
Can i remotely have the virus scan the computer again after the victim has already installed it?

### ISSUE THREAD

**Issue by hmohar101** [Rdimo/Hazard-Token-Grabber-V2#438]
Like it only sent 1 webhook with all the info as soon as it was installed on my spare laptop, I was wanting to see if there was a way I can make it get all the info again. (as discord tokens expire after 24 hours) If you could let me know how/if that is possible, i'd greatly appreciate it!

**Comment by GodFather227** [comment]
Yeah that should be too bad I don’t think

**Comment by GodFather227** [comment]
You can add a command that adds the exe to startup

**Comment by hmohar101** [comment]
> You can add a command that adds the exe to startup

How would I go about that? sorry i'm not very experienced with coding, kinda just going off youtube videos and shit lol

**Comment by GodFather227** [comment]
> > You can add a command that adds the exe to startup
> 
> How would I go about that? sorry i'm not very experienced with coding, kinda just going off youtube videos and shit lol

Add me on discord K.Dot (just join rdimo server)

**Comment by Rdimo** [comment]
no, what you're referring to is a R.A.T. Which v2 is not
