### ISSUE TITLE
when creating a exe it says: cant find (name of exe i chose).spec

### ISSUE THREAD

**Issue by Poplix09** [Rdimo/Hazard-Token-Grabber-V2#44]

**Comment by Rdimo** [comment]
wdym

**Comment by Rdimo** [comment]
did you put the filename as name.spec?

**Comment by RecklessRascull** [comment]
Did you put spaces in the name? If so, try removing the spaces. You can add them back after the EXE is built.

**Comment by Rdimo** [comment]
got dauym, ty again @RecklessRascull
