### ISSUE TITLE
Can't retrieve Browser Discord token

### ISSUE THREAD

**Issue by dexeey** [Rdimo/Hazard-Token-Grabber-V2#441]
![image](https://user-images.githubusercontent.com/80825816/178141674-648994c1-0093-4cab-892c-8fd274eca097.png)
I tested the grabber (with my account) but the grabber do not retrieve the browser Discord token

**Comment by Resisst** [comment]
i believe there may be a glitch in the mainframes of the dialog. right click the download button and press copy link and paste it here so that i can diagnose the problem.
