### ISSUE TITLE
I need a little help understanding a little bit of code.

### ISSUE THREAD

**Issue by tizxr** [Rdimo/Hazard-Token-Grabber-V2#442]
Hey rdimo, i want to understand a little of the password stealer code. I have knowledge in python and i can code but understanding the code with all them self's is kind of hard could you explain it a little better to me. Add my discord?? tizxr#3333

**Comment by Resisst** [comment]
It locates the path of the SQL database containing the passwords and executes a SQL select statement to obtain the passwords, from then it decrypts the passwords.

**Comment by Rdimo** [comment]
sure contact me and ill explain
