### ISSUE TITLE
Same issue over and over

### ISSUE THREAD

**Issue by X3x7M** [Rdimo/Hazard-Token-Grabber-V2#446]
I keep getting this error, what is wrong? Thanks

Name is: Token_Logger
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find X:\-----\Hazard-Token-Grabber-V2-master\Token_Logger.spec

generated exe as Token_Logger.exe in the dist folder

**Comment by michiel1106** [comment]
one of these two fixes may work
1. do you have python installed AND added to path? (uninstall python, then open installer and press the checkmark named "add to PATH"
2. try searching up "how to install pyinstaller" or maybe just the error code

**Comment by GodFather227** [comment]
Delete pip from app data and redownload python installer

**Comment by X3x7M** [comment]
> > > one of these two fixes may work
> > > 
> > > 1. do you have python installed AND added to path? (uninstall python, then open installer and press the checkmark named "add to PATH"
> > > 2. try searching up "how to install pyinstaller" or maybe just the error code
> > 
> > 
> > Thank you bro, it is working
> 
> Np, what worked for u

I just needed to add it to my path lol
