### ISSUE TITLE
cant make a stub

### ISSUE THREAD

**Issue by ujal1** [Rdimo/Hazard-Token-Grabber-V2#453]
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find C:\Users\Admin\Desktop\Hazard-Token-Grabber-V2-master\test.spec

**Comment by chris2rich** [comment]
pip install pyinstaller in cmd

**Comment by euclidssss** [comment]
skid add to path

**Comment by Smug246** [comment]
> 'pyinstaller' is not recognized as an internal or external command, operable program or batch file. The system cannot find the file specified. The system cannot find the file specified. Could Not Find C:\Users\Admin\Desktop\Hazard-Token-Grabber-V2-master\test.spec

if u added to path and is still doesnt work. pip install pyinstaller
