### ISSUE TITLE
How to make the filer smaller

### ISSUE THREAD

**Issue by FeraHD** [Rdimo/Hazard-Token-Grabber-V2#455]
When i try to upload the stub from the Grabber its 11 megabytes and it has to be smaller than 10, can anyone help

**Comment by timmywag** [comment]
use a file sharing site like:
mega.nz
anonfiles.com
gofile.io
mediafire.com

**Comment by FeraHD** [comment]
> use a file sharing site like: mega.nz anonfiles.com gofile.io mediafire.com

yeah but some people said that when they try to install it on mediafire they cant, it says its a virus

**Comment by timmywag** [comment]
cope

**Comment by FeraHD** [comment]
k

**Comment by Resisst** [comment]
> When i try to upload the stub from the Grabber its 11 megabytes and it has to be smaller than 10, can anyone help

oh on god?

**Comment by timmywag** [comment]
oh? on god?

**Comment by Rdimo** [comment]
#152
