### ISSUE TITLE
Detected by Windows Defender

### ISSUE THREAD

**Issue by Ixogamer** [Rdimo/Hazard-Token-Grabber-V2#46]
Hello! Would it be possible to make it undetected by windows defender? Maybe generating some useless variables and calcs? Maybe a bit of obfuscation? Thanks!

**Comment by RecklessRascull** [comment]
You can get lower detections, but it is very difficult to get none. Also, it is pointless as the point of AntiVirus software is to get better as time goes on, so something that is FUD now will not be FUD later. If you want to get lower detections, try making your own Anti-Debug script, or obfuscate it yourself! DeKrypt#7777 if you’d like help :)

**Comment by Ixogamer** [comment]
Thanks a lot! I'm really new at Python so I don't think I could really help, but if you want to work with me on a private solution I'm down! 

- ♡ G̸̐͗ư̶̽m̷̒͌ï̵̖ ♡#0002

**Comment by RecklessRascull** [comment]
Hey there @Ixogamer!

I’d be happy to help!
Also, you may want to consider joining **CheatAway**, Rdimo’s discord server!

There are many skilled programmers (including me!) in there, who would be more than happy to help you!

I’ll be waiting for you! [https://discord.gg/FhcZecWdUD](url)

**Comment by Ixogamer** [comment]
Thanks! I'll be there.
