### ISSUE TITLE
issue with Crypto module

### ISSUE THREAD

**Issue by dadsondick123** [Rdimo/Hazard-Token-Grabber-V2#463]
![image](https://user-images.githubusercontent.com/109877970/180624953-f1229dcf-8f55-4333-9556-386b44476c22.png)

**Comment by dadsondick123** [comment]
![image](https://user-images.githubusercontent.com/109877970/180624800-07d930b4-aa02-4a87-b622-b610739e6fc2.png)

**Comment by timpl999** [comment]
Isnt crypto module paid tho

**Comment by Rdimo** [comment]
> Isnt crypto module paid tho

no it's not xd
all pip modules are free ofc

**Comment by Rdimo** [comment]
#323
