### ISSUE TITLE
Token protector blocking grabber

### ISSUE THREAD

**Issue by Xeneht** [Rdimo/Hazard-Token-Grabber-V2#471]
![image](https://user-images.githubusercontent.com/99096857/181347237-9afc5bcf-6ace-4f5b-b667-f2bf82f5ff88.png)

**Comment by Rdimo** [comment]
its not the token protector blocking it, its windows itself denying access from deleting it. 
And are you on windows 7 or sum shit? update to win10 atleast

**Comment by Xeneht** [comment]
i have windows 10
