### ISSUE TITLE
How do i delete it

### ISSUE THREAD

**Issue by lukaz34** [Rdimo/Hazard-Token-Grabber-V2#477]
I ran i on my own computer ind now when i try to turn on hidden files it says 'this page has been blocked by your it-adminisrator'
Please Help!

**Comment by timmywag** [comment]
maybe dont use it on a school/work computer

**Comment by lukaz34** [comment]
> maybe dont use it on a school/work computer

but how do i delete it?

**Comment by PandoricGalaxy** [comment]
> > maybe dont use it on a school/work computer
> 
> but how do i delete it?

Is it pc or ur school/college computer

**Comment by Rdimo** [comment]
#83
