### ISSUE TITLE
DLL load failed while importing win32crypt.

### ISSUE THREAD

**Issue by JustGuardian** [Rdimo/Hazard-Token-Grabber-V2#48]
On victim pc, when i launch the compiled exe it gives me this error:
ImportError: DLL load failed while importing win32crypt: The specified module could not be found.
I have done all the things in the ReadMe file so idk where I'm wrong.
Please help.

**Comment by JustGuardian** [comment]
NVM fixed changing the import to "import win32api"

**Comment by DreamyDidIt** [comment]
> 
Could you please go more in detail how you fixed it. I dont know shit about python!!!

**Comment by Rdimo** [comment]
@JustGuardian importing win32api instead of win32crypt will just end up in a bunch of errors since it doesn't have that function, install pywin32 by opening cmd and typing `pip install pypiwin32` and it should work after that
