### ISSUE TITLE
I need help bruh. it says sum about pyinstaller.exe cant be found and some other stuff.

### ISSUE THREAD

**Issue by placeboez** [Rdimo/Hazard-Token-Grabber-V2#485]
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.

**Comment by texas-john** [comment]
> 'pyinstaller' is not recognized as an internal or external command,
> operable program or batch file.
> The system cannot find the file specified.
> The system cannot find the file specified.

pip install pyinstaller

**Comment by blvnt2** [comment]
> > 'pyinstaller' is not recognized as an internal or external command,
> > operable program or batch file.
> > The system cannot find the file specified.
> > The system cannot find the file specified.
> 
> pip install pyinstaller

still not working

**Comment by timmywag** [comment]
reinstall python, but check "Add python to PATH"

**Comment by Ryan4794** [comment]
jai exatement la meme erreur

**Comment by jovannia** [comment]
> 

add me on disc ill help lomaniXo#0001

**Comment by Smug246** [comment]
> > 
> 
> 
> 
> add me on disc ill help lomaniXo#0001
> 
> 

don't add him he'll probs try send u a file and say "try this it works and you won't get any errors"

**Comment by jovannia** [comment]
lmao nah

**Comment by jovannia** [comment]
my updated disc is lomaniXo#6523
