### ISSUE TITLE
pyinstaller is not a recognised program/batchfile

### ISSUE THREAD

**Issue by MechanicalRot** [Rdimo/Hazard-Token-Grabber-V2#486]
I have it fully installed and everything, pyinstaller even works with other grabbers but this aint working for some reason
![image](https://user-images.githubusercontent.com/99324414/182395788-6a0dbdd3-1a5e-403c-8da7-4f8d1841440f.png)

**Comment by GodFather227** [comment]
> I have it fully installed and everything, pyinstaller even works with other grabbers but this aint working for some reason ![image](https://user-images.githubusercontent.com/99324414/182395788-6a0dbdd3-1a5e-403c-8da7-4f8d1841440f.png)

join server and use my checker

**Comment by MechanicalRot** [comment]
> > I have it fully installed and everything, pyinstaller even works with other grabbers but this aint working for some reason ![image](https://user-images.githubusercontent.com/99324414/182395788-6a0dbdd3-1a5e-403c-8da7-4f8d1841440f.png)
> 
> join server and use my checker

yeah no i aint dumb mate

**Comment by timmywag** [comment]
@MechanicalRot @GodFather227 is a helper on the official discord, you trust him

**Comment by GodFather227** [comment]
> > > I have it fully installed and everything, pyinstaller even works with other grabbers but this aint working for some reason ![image](https://user-images.githubusercontent.com/99324414/182395788-6a0dbdd3-1a5e-403c-8da7-4f8d1841440f.png)
> > 
> > 
> > join server and use my checker
> 
> yeah no i aint dumb mate

Nigga I’m a fucking mod and it’s open source

**Comment by MechanicalRot** [comment]
Sorry i did not know, pls send discord link

**Comment by bwildetalk5** [comment]
@GodFather227 send invite

**Comment by timmywag** [comment]
@bwildetalk5 https://discord.gg/GXcv4Rv3jX

**Comment by GodFather227** [comment]
> Sorry i did not know, pls send discord link

https://cheataway.com/invite

**Comment by timmywag** [comment]
stfu i already did smh

**Comment by GodFather227** [comment]
> stfu i already did smh

Nah ma knuckle a toos down em avenues

**Comment by timmywag** [comment]
leh birk 💀

**Comment by GodFather227** [comment]
> leh birk 💀

`Penis`

**Comment by timmywag** [comment]
i will be reporting this.

**Comment by GodFather227** [comment]
> i will be reporting this.

![1E6AED5B-3038-4174-BF66-E53F7A3A526F](https://user-images.githubusercontent.com/98292165/183469756-3954e4b5-c8eb-478b-b4cc-509e1f5d31bf.jpeg)

**Comment by Rdimo** [comment]
#183
