### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Serpensin** [Rdimo/Hazard-Token-Grabber-V2#492]
About one year ago I wrote a small app that allows me to download emojis from servers I'm part of.
For that reason I needed a way to grab the token. Back then it was pretty easy, because the token always started with "mfa.".
But since they changed it I couldn't figure it out on how to get it again.

Can someone help me to change this script so it only shows the discord token?
The other stuff has to be removed because this one is a clean app.

**Comment by GodFather227** [comment]
> About one year ago I wrote a small app that allows me to download emojis from servers I'm part of. For that reason I needed a way to grab the token. Back then it was pretty easy, because the token always started with "mfa.". But since they changed it I couldn't figure it out on how to get it again.
> 
> Can someone help me to change this script so it only shows the discord token? The other stuff has to be removed because this one is a clean app.

1.) tokens never always started with mfa (only 2fa ones)
2.) why tf u need someones token to download emoji's lmao
3.) it sends tokens after the other person runs
4.) half of this is common sense things

**Comment by Serpensin** [comment]
1.) Even the mfa ones changed. (I tested it with my one.)
2.) Otherwise I don't get access to the guild. That's the reason why you can only download emojis from servers you're a part of.
3.) Yeah I know. I just wanted to get rid of everything but the grabber part.
