### ISSUE TITLE
help me pleas

### ISSUE THREAD

**Issue by Ryan4794** [Rdimo/Hazard-Token-Grabber-V2#493]
![image](https://user-images.githubusercontent.com/110686855/183222714-e2918357-15d9-42f6-9170-101551fbb4d9.png)

Enter the exe name : a

Name is: a
'pyinstaller' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Le fichier spécifié est introuvable.
Le fichier spécifié est introuvable.
Impossible de trouver C:\Users\dehme\Desktop\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\a.spec

generated exe as a.exe in the dist folder

Appuyez sur une touche pour continuer...

**Comment by Smug246** [comment]
i'm not french but i'm pretty sure you need add python to you path

**Comment by LisaPlaysVS** [comment]
> 

how do i do this im so confused myself

**Comment by Ryan4794** [comment]
> 

but that's what i did...

**Comment by GodFather227** [comment]
> but that's what i did... and its still not working

There is a folder named scripts that u have to add too

**Comment by Ryan4794** [comment]
How should I do ?

**Comment by PandoricGalaxy** [comment]
> How should I do ?

Add the folder scripts to path. Now Google it how to

**Comment by Rdimo** [comment]
#183
