### ISSUE TITLE
It's a read only file

### ISSUE THREAD

**Issue by harryflax** [Rdimo/Hazard-Token-Grabber-V2#496]
im on kali linux trying to run this and i can't replace the webhook file as it is read only.

**Comment by timmywag** [comment]
do you not know how to use linux?
i suggest using whatever brain cells you have less to understand basic computing.

**Comment by harryflax** [comment]
Yeah ik bruh 😭 nah I figured it out I had a mind blank

**Comment by timmywag** [comment]
ah i see
