### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Kingofthepirates12** [Rdimo/Hazard-Token-Grabber-V2#50]
Failed to execute script "main" due to unhandled exception: No module named psutil
Traceback(most recent call last); 
File "main.py", line 8, in <module>
ModuleNotFoundError: No module named 'psutil'
Please help this is the error I got

**Comment by Ixogamer** [comment]
Are you trying to compile it manually? Maybe try `pip install psutil`

**Comment by R3KI10** [comment]
> Are you trying to compile it manually? Maybe try `pip install psutil`

I treid to install psutil but i got an error

**Comment by Kingofthepirates12** [comment]
> Are you trying to compile it manually? Maybe try `pip install psutil`

I did not install it manually, when I turned the program into an .exe it game me this error.
![image](https://user-images.githubusercontent.com/96668478/147419347-777b6aad-8038-4db6-a853-d71aa108c0d1.png)

**Comment by RecklessRascull** [comment]
> > Are you trying to compile it manually? Maybe try `pip install psutil`
> 
> I tried to install psutil but i got an error

What is this error? Perhaps explaining it further could help me fix it.
