### ISSUE TITLE
Not a bug or question just need some clarification 

### ISSUE THREAD

**Issue by deepan-py** [Rdimo/Hazard-Token-Grabber-V2#503]
What happens if the victim deleted the exe file but the exe file was generated and executed with startup true?

**Comment by AltyKing** [comment]
> What happens if the victim deleted the exe file but the exe file was generated and executed with startup true?

The file is going to clone itself to `shell:startup` 
If the user deletes the file you will still recieve data trough the webhook
The only con here is that the user can delete the file in `shell:startup` and its not going to work anymore

**Comment by timmywag** [comment]
it goes in ur mom frfrfr
