### ISSUE TITLE
i keep getting psutil error

### ISSUE THREAD

**Issue by 2Luciferuwu2** [Rdimo/Hazard-Token-Grabber-V2#51]
![image](https://user-images.githubusercontent.com/92219129/147427608-4b5a68cd-8dda-464e-8f73-e3e323feeda5.png)

**Comment by RecklessRascull** [comment]
Simple fix!
Open command prompt, and type `pip install psutil`

Now run the build-exe.bag again and it should work fine! :)

**Comment by Kingofthepirates12** [comment]
I

> Simple fix! Open command prompt, and type `pip install psutil`
> 
> Now run the build-exe.bag again and it should work fine! :)

I did this and I am still getting the same error, I ran in cmd then ran the setup file. Still gave me the error.

**Comment by RecklessRascull** [comment]
@Kingofthepirates12 

What python version are you using?
If you’re using anything above 3.9.8 consider downgrading from that version to version 3.9.7 (Most stable version)

Also, while installing, make sure to enabled “Add python to PATH”
After you have done all of this, you should be good to go!

Good luck! :)

**Comment by Rdimo** [comment]
ty @RecklessRascull
