### ISSUE TITLE
I get this error about pyinstaller

### ISSUE THREAD

**Issue by Xscouser** [Rdimo/Hazard-Token-Grabber-V2#52]
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find C:\Users\Uporabnik\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\dyno.spec

**Comment by Kingofthepirates12** [comment]
When you install python make sure to click the box that includes path.

**Comment by Groppy-main** [comment]
nope, that's not the issue, I added to PATH yet it says this

**Comment by Xscouser** [comment]
I installed everything and it still says this

**Comment by Groppy-main** [comment]
go to CMD and enter "pip install pyinstaller"

**Comment by Xscouser** [comment]
Groppy-main   I did that too and it still doesnt work

**Comment by Rdimo** [comment]
if `pip install pyinstaller` didnt work, do you have multiple pythons installed by any chance?

**Comment by idknoob91** [comment]
> 

yea i get this error too

**Comment by Xscouser** [comment]
Rdimo.. No I installed it only once.

**Comment by Stilexe** [comment]
i get this error too
