### ISSUE TITLE
'pyinstaller' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Groppy-main** [Rdimo/Hazard-Token-Grabber-V2#53]
I did both methods, using the setup.bat and manually compiling and both times I get the same error 
"'pyinstaller' is not recognized as an internal or external command,
operable program or batch file."
(Python is added to PATH so that's not the issue)

Please help

**Comment by mikvlll** [comment]
same

**Comment by Groppy-main** [comment]
Found solution, just install pyinstaller using CMD (pip install pyinstaller)
