### ISSUE TITLE
Where do i find the new password

### ISSUE THREAD

**Issue by 28Vitoo** [Rdimo/Hazard-Token-Grabber-V2#55]
the readme says it also gives you the password of the victim if they change it but where do i find the changed password

**Comment by Kingofthepirates12** [comment]
I assume they would have to run the exe again.

**Comment by 28Vitoo** [comment]
but noone does this

**Comment by Rdimo** [comment]
no they do not have to run the exe again @Kingofthepirates12
and the new password ends up in the server where you input your webhook
