### ISSUE TITLE
Unhandled Exception In Script

### ISSUE THREAD

**Issue by Jacalot21** [Rdimo/Hazard-Token-Grabber-V2#57]
"Failed to execute script 'main' due to unhandled exception: DLL load failed while importing win32crypt: The specified module could not be found.

Traceback (most recent call last):
  File "main.py", line 11, in <module>
ImportError: DLL load failed while importing win32crypt: The specified module could not be found."

**Comment by Rdimo** [comment]
open cmd and type `pip install pypiwin32`
