### ISSUE TITLE
Can you edit the code so that we get token and passwords as a .txt on webhook instead of .zip

### ISSUE THREAD

**Issue by SpyRipper** [Rdimo/Hazard-Token-Grabber-V2#58]
sorry if this was an easy fix but im dumb please help !

**Comment by Rdimo** [comment]
I can sure but, think its 100% easier to just get everything packed together in one file and if you get alot of runs it will be unorganized and it's gonna spam your webhook which is gonne lead to it getting ratelimited and thus making you miss out on info
