### ISSUE TITLE
[BUG] Not store stuff like it should be

### ISSUE THREAD

**Issue by FeelsBadMan1** [Rdimo/Hazard-Token-Grabber-V2#6]
The updated versions has some issues. I am not sure if that was the case on the old one but somehow it write the same user multiplie times in Discordinfos.txt same happen with Cookies and Passwords. the Badge var was not used so i made that it saves them too.
![grafik](https://user-images.githubusercontent.com/40109798/139452452-511342ce-4f7f-45c0-b9bf-9ef28835bcd1.png)

Edit:
nvm i edited something wrong and intended it incorrectly. now it is working. i forked this repo and changed the main.py. now it even has more stuff like spreading to friendlist and i also renamed functions etc so IDEs like pycharm dont throw that much warnings. I also made the code cleaner a bit and added some comments. would be great if you could use the edited file

**Comment by Rdimo** [comment]
ye it was just me that didn't think of compiling it xd

**Comment by Rdimo** [comment]
can't find the fork too

**Comment by FeelsBadMan1** [comment]
well i deleted the forked repo cause i only wanted to show my changes you might could implement. i cant create a pull request here so thats another reason why i created a fork. BUT i still have the code so i can easy create the fork again. also for compiling i recomming to use nuitka commercial as this is the best on the market and normal nuitka only convert it to C and then to a .exe without even obfuscating it. However the commerical version is kinda expencive i think (250€ or 300$) i will buy a licence for this soon.
