### ISSUE TITLE
How to remove the discord injection

### ISSUE THREAD

**Issue by TheRockObama942** [Rdimo/Hazard-Token-Grabber-V2#61]
Hi.

I accidentally ran this on my own computer. How do I remove it? Thank you.

I have a Windows 10 machine btw

**Comment by throwawayorsoe** [comment]
Go to this directitory:

**C:\Users\YOURUSERNAMEHERE\AppData\Local\Discord\app-1.0.9003\resources\app**

**Comment by Rdimo** [comment]
Open this directory:
**C:\Users\YOURUSERNAMEHERE\AppData\Local\Discord\app-1.0.9003\modules\discord_desktop_core-1\discord_desktop_core\index.js**
Then open the index.js file and then just replace everything in there with `module.exports = require('./core.asar');`
