### ISSUE TITLE
Error when running the generated exe file

### ISSUE THREAD

**Issue by Markusklarcus** [Rdimo/Hazard-Token-Grabber-V2#62]
after running the exe file to test it out i get an error (attached picture)
Please help
![image](https://user-images.githubusercontent.com/79845920/148535980-33e45952-eb46-4207-a555-9c2e249c45ea.png)

**Comment by Rdimo** [comment]
read the [setup](https://github.com/Rdimo/Hazard-Token-Grabber-V2#setting-up-hazard-token-grabberv2)
