### ISSUE TITLE
what to do ?

### ISSUE THREAD

**Issue by R3KI10** [Rdimo/Hazard-Token-Grabber-V2#63]
![Screenshot (858)](https://user-images.githubusercontent.com/89774490/148676642-71d2eef9-e6b9-45ca-a139-3155399eb775.png)

**Comment by Rdimo** [comment]
try reinstalling [pyautogui](https://pypi.org/project/PyAutoGUI/). If that doesn't work, check [this](https://github.com/asweigart/pyautogui/issues/598) post and see if it helps
