### ISSUE TITLE
issue with setup.bat

### ISSUE THREAD

**Issue by extrajumprcl** [Rdimo/Hazard-Token-Grabber-V2#64]
![image](https://user-images.githubusercontent.com/89422260/149231733-7b4b75e7-72c1-40a9-9db1-80724feb96d2.png)
idk why its like this.

**Comment by Rdimo** [comment]
if your gonna start the batch file by a command you need to be in the same directory because as of right now your in your downloads folder and trying to start the batch file when it's somewhere else, just double click the build-exe.bat file instead, alot easier
