### ISSUE TITLE
Empty cookies/passwords

### ISSUE THREAD

**Issue by SUPREME691** [Rdimo/Hazard-Token-Grabber-V2#68]
Not gettng their cookies/ chrome psswords etc the file is empty

**Comment by SUPREME691** [comment]
![done](https://user-images.githubusercontent.com/97758674/149569557-71e4db6d-0429-4357-a10a-b659fdd2b359.PNG)

**Comment by Rdimo** [comment]
oh, can fix that if you want

**Comment by Rdimo** [comment]
fixed now
