### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by OoniUni** [Rdimo/Hazard-Token-Grabber-V2#7]
Ey man number 1 how come you went missing for a few days?? Your page kept getting 404 error not found problems. And about the feature suggestion it would be nice if we can set the file to any size we want like by dumping a bunch of useless files so that sometimes its not too easy to assume its anything but what its trying to be like..... What CSGO mod menu be like less than 20kb

**Comment by iGetUploaded** [comment]
His account got flagged that's why he was gone

**Comment by OoniUni** [comment]
Oh damn glad he's back

**Comment by Rdimo** [comment]
ye got flagged for some reason but contacted the support and managed to get it unflagged, but a file bumper could sure be a thing, let me look into that!
