### ISSUE TITLE
Discord inject not working

### ISSUE THREAD

**Issue by VerstreuteSeele** [Rdimo/Hazard-Token-Grabber-V2#72]
Hey.

Nice grabber, however the discord injection isn't doing anything. I tested it on my own account and adding a card or changing the password will not send a new webhook message. Tried it on two machines, one freshly set up just with discord and one with Betterdiscord. Any ideas on how to debug this?

**Comment by Rdimo** [comment]
idk ill look into it, discord changes their properties quite often so might need to update those

**Comment by VerstreuteSeele** [comment]
> idk ill look into it, discord changes their properties quite often so might need to update those

yeah. I found what looks like the "original" for that injection, called PirateStealer. theirs works fine however adding a card doesnt return an address and they said they are too lazy to fix it :/

Might wanna look into theirs. should make everything easier

**Comment by VerstreuteSeele** [comment]
In case you care:

https://github.com/Stanley-GF/PirateStealer/
https://github.com/Stanley-GF/PirateStealer/issues/47/

**Comment by Rdimo** [comment]
yea already know about it, that's partially where I got the injection from but just made modifications from it, dont want to completely rip the code and skid it straight off

**Comment by VerstreuteSeele** [comment]
> yea already know about it, that's partially where I got the injection from but just made modifications from it, dont want to completely rip the code and skid it straight off

understandable and also didnt expect you to straight up skid it :) Just saying it will help with the new field names of discords stuff. Also, would be a real banger if you could fix the issue I sent you they are too lazy to work on

**Comment by Rdimo** [comment]
sure why not, got nothing better to do tbh, fixing some bugs with hazard rn and updating this grabber rn to make it more efficient and smaller in size but ill look into the injection soon for sure

**Comment by Rdimo** [comment]
thank you for telling @VerstreuteSeele, working on the injection now and made the credit card stealer work again

**Comment by VerstreuteSeele** [comment]
hmm.. it only works partialy for me. It returns undefined for the address values @Rdimo

**Comment by VerstreuteSeele** [comment]
```
Country: undefined
State undefined
City undefined
ZIP: undefined
Street: undefined
```

**Comment by Rdimo** [comment]
but you get the cc?

**Comment by VerstreuteSeele** [comment]
lmfao aight.

and yeah, cc works perfectly fine

**Comment by VerstreuteSeele** [comment]
oh btw, I really dont want to expect too much from you, but piratestealer also fails to return the 2fa codes. so that's another good selling point for using yours if you can fix it somehow

**Comment by Rdimo** [comment]
made stealers ages ago that stole 2fa codes, but didnt want to implement it to hazard since the file size may bump up, but reduced it now by quite alot so can implement it if you want

**Comment by VerstreuteSeele** [comment]
would love to see it, yeah

granted, all that (address and 2fa codes) can easily be accessed yourself by just logging in since we can get the password but having it all done by a webhook is just so much nicer

**Comment by Rdimo** [comment]
yea understand that, can implement that rn then, got nothing better to do

**Comment by Rdimo** [comment]
or ill do it after this game, shitting on kids in overwatch rn

**Comment by VerstreuteSeele** [comment]
:D

**Comment by VerstreuteSeele** [comment]
haha bet. btw I sent you an FA on discord if you wanna accept

**Comment by Rdimo** [comment]
send me a dm and ill accept, got so many friend requests so dont know which one is you

**Comment by VerstreuteSeele** [comment]
cant since we dont share a server. its ClaraCrazy

**Comment by Rdimo** [comment]
join ma [discord](https://cheataway.com/) and dm the owner

**Comment by Rdimo** [comment]
to lazy to look up your dc name

**Comment by VerstreuteSeele** [comment]
yeah did that. sent a dot lol

**Comment by Rdimo** [comment]
fixed now
