### ISSUE TITLE
Error in execution

### ISSUE THREAD

**Issue by joshh01** [Rdimo/Hazard-Token-Grabber-V2#73]
Everything works fine - installing, setup, running, although i keep getting an error message:
![image](https://user-images.githubusercontent.com/88389161/150699438-63a377df-ee73-4a06-a2c3-b42ad57df79c.png). 
I figured this is a python issue rather than a specific code issue, and wondered how to fix it.

Also, not sure if this is going to happen if sent to another person, just wanted to clear this up.

**Comment by VerstreuteSeele** [comment]
you need to install pywin32 before compiling it. should be in the requirements file anyways.

pip install pywin32

**Comment by Rdimo** [comment]
do `pip install pypiwin32` pywin32 is outdated and not maintained anymore so it wont work for this grabber
