### ISSUE TITLE
Cant install pyinstaller idk why :) pls help

### ISSUE THREAD

**Issue by LOSEARDES77** [Rdimo/Hazard-Token-Grabber-V2#74]

**Comment by Rdimo** [comment]
you tried `pip install pyinstaller`?

**Comment by LOSEARDES77** [comment]
yes and it says succesfully installed but your bat scrypt dosn't work foto here
![image](https://user-images.githubusercontent.com/84414230/151216093-d01e0513-a8d4-42d3-ab66-a2cadb91b6d4.png)

**Comment by LOSEARDES77** [comment]
ok idk how but i think i got it it ws just that the pyinstaller scrypt wasn't in the right directory or somthing like that but tysm for your attention <3

**Comment by LOSEARDES77** [comment]
ok now i noticed it dosn't work at all. when you execut the exe file this appears 
![image](https://user-images.githubusercontent.com/84414230/151233709-be40158c-88a2-4e6b-ab8e-486cd2c03ea6.png)

full text content of the imagen `Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32api.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pywintypes.py", line 129, in <module>
  File "pywintypes.py", line 44, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['C:\\Users\\Victo\\AppData\\Local\\Temp\\_MEI230642\\base_library.zip', 'C:\\Users\\Victo\\AppData\\Local\\Temp\\_MEI230642\\lib-dynload', 'C:\\Users\\Victo\\AppData\\Local\\Temp\\_MEI230642']
`

**Comment by Rdimo** [comment]
what da hell

**Comment by Rdimo** [comment]
pywintypes is a part of pywin32 so try and install it `pip install pypiwin32`
