### ISSUE TITLE
More browser support

### ISSUE THREAD

**Issue by AlexGamerNice** [Rdimo/Hazard-Token-Grabber-V2#76]
I tested this on myself just for fun. I went ahead and viewed my cookies. (I have multiple web browsers installed.) It didn't show and of the main cookies I use. Only good chrome ones. Like .roblosecurity Roblox login discord token etc. Is it possible for instead of just google chrome you do it for all web browsers too? Brave, Opera GX Firefox, and not just google chrome. I can tell that some people might not like this idea. Or too hard to program. But its good otherwise

**Comment by Rdimo** [comment]
if anything, to make it steal from multiple browsers is easy, but dont want to make this too op for a free grabber, if you want it to grab more you can order one from me

**Comment by AlexGamerNice** [comment]
How much money will it cost?

**Comment by Rdimo** [comment]
depends on what you want to steal, contact on discord if intrested
