### ISSUE TITLE
Can't run exe

### ISSUE THREAD

**Issue by fluencies** [Rdimo/Hazard-Token-Grabber-V2#8]
Whenever I try and run the exe this msg comes up.
![image](https://user-images.githubusercontent.com/93334137/139510558-362cd757-f760-481f-8e60-9a3fb39a65d5.png)
is it something I did wrong?

**Comment by OoniUni** [comment]
I believe you need to download the ZIP of the Code itself I think people call it source basically... Download the file in   the "Code" box on the softwares page and when its done open the install_requirements.cmd thing THEN you can run the exe

**Comment by Rdimo** [comment]
fixed it now, download new version
