### ISSUE TITLE
how do i make this exe file

### ISSUE THREAD

**Issue by kamex33** [Rdimo/Hazard-Token-Grabber-V2#82]
how do i make this exe file

**Comment by magnouni** [comment]
pyinstaller

**Comment by addi00000** [comment]
> how do i make this exe file

1. `python -m pip install PyInstaller`
2. `python -m PyInstaller "filename.py"`

There's more to it but that's the bare basics.

**Comment by Pitywithyou** [comment]
you can create a exe when you first write in cmd  at first pip pyinstaller   then  pip install auto-py-to-exe and then write auto-py-to-exe

**Comment by Rdimo** [comment]
its stated in the readme
