### ISSUE TITLE
How to remove this from your device if you log by someone else

### ISSUE THREAD

**Issue by RedShadow5298** [Rdimo/Hazard-Token-Grabber-V2#83]

**Comment by RecklessRascull** [comment]
Reinstall discord and change your passwords

**Comment by RedShadow5298** [comment]
ok thx but what about the chrome grabber?. Password and cookies will update. Or it just gone?

**Comment by RecklessRascull** [comment]
its gone just change your passwords once you change the passwords it wont log them again

**Comment by Rdimo** [comment]
#37
