### ISSUE TITLE
'pyinstaller' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by wijoFN** [Rdimo/Hazard-Token-Grabber-V2#88]
I put in the name and this is what it says what do i do ?

Enter the exe name : shoebot

Name is: shoebot
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find C:\Users\sconn\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master\shoebot.spec

generated exe as shoebot.exe

C:\Users\sconn\Downloads\Hazard-Token-Grabber-V2-master\Hazard-Token-Grabber-V2-master>

**Comment by wijoFN** [comment]
if anyone knows how dm me on disc  wijo#7056

**Comment by danielsabox** [comment]
I have the exact same issue pls help

**Comment by danielsabox** [comment]
I figured it out uninstall python, restart your computer, reinstall python and check the PATH option when installing. It worked for me

**Comment by Rdimo** [comment]
pip install pyinstaller

**Comment by Rdimo** [comment]
documented here #99
