### ISSUE TITLE
EXE Not running

### ISSUE THREAD

**Issue by MechanicalRot** [Rdimo/Hazard-Token-Grabber-V2#90]
This message appears when I try to run the EXE
![image](https://user-images.githubusercontent.com/99324414/153166644-c273b300-4f4b-4b52-8df8-b29102fbef78.png)

**Comment by juststfu** [comment]
what exe

**Comment by RecklessRascull** [comment]
This is a weird error not caused by the script but with your installation of python. What python version do you use?

**Comment by Rdimo** [comment]
issue is alreayd open #91
