### ISSUE TITLE
The handle is invalid

### ISSUE THREAD

**Issue by xxebo** [Rdimo/Hazard-Token-Grabber-V2#91]
![image](https://user-images.githubusercontent.com/85994014/153543020-b3ea111a-25cf-492b-894c-3fbf1ef42930.png)

**Comment by xxebo** [comment]
Ohk

**Comment by xxebo** [comment]
@dekrypted it don`t work 
you have any other way?

**Comment by xxebo** [comment]
![image](https://user-images.githubusercontent.com/85994014/153698367-0a4839d8-1d65-4162-abf9-495e0e20820d.png)

**Comment by dekrypted** [comment]
Eh… Maybe look it up. I’ve never seen this error

**Comment by Rdimo** [comment]
fixed in new version hopefully
