### ISSUE TITLE
Discord Server Problem

### ISSUE THREAD

**Issue by SarnaxLii** [Rdimo/Hazard-Token-Grabber-V2#92]
I can't log into your server. Don't know if you banned me or if the server is disabled. if so please contact me back

**Discord** : Sarnax#9999

**Comment by FuckingToasters** [comment]
Same happened for me so i thought I'm banned for no reason. rdimo is offline too long and because others have the problem told i think the server and he got termed. I also tried to join on another account and it seem that the invite is just invalid.

**Comment by Rdimo** [comment]
sadly server got termed, go to https://cheataway.com/ to get new discord
